// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_COMP_HOOK_H
#define _SQUARELINE_PROJECT_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_cmpdatetimebar_create_hook(lv_obj_t * comp);
void ui_comp_cmpfocuscell_create_hook(lv_obj_t * comp);
void ui_comp_cmpmodetoggle_create_hook(lv_obj_t * comp);
void ui_comp_cmptableheader_create_hook(lv_obj_t * comp);
void ui_comp_cmptablerow4col_create_hook(lv_obj_t * comp);
void ui_comp_div__create_hook(lv_obj_t * comp);
void ui_comp_num_create_hook(lv_obj_t * comp);
void ui_comp_paneleg_create_hook(lv_obj_t * comp);
void ui_comp_rowenter_create_hook(lv_obj_t * comp);
void ui_comp_rowitem_create_hook(lv_obj_t * comp);
void ui_comp_rowitem1_create_hook(lv_obj_t * comp);
void ui_comp_rowlabel_create_hook(lv_obj_t * comp);
void ui_comp_rowswitch_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
