// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT dialogeg

lv_obj_t * ui_dialogeg_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_dialogeg;
    cui_dialogeg = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_dialogeg, 306);
    lv_obj_set_height(cui_dialogeg, 133);
    lv_obj_set_x(cui_dialogeg, 400);
    lv_obj_set_y(cui_dialogeg, 130);
    lv_obj_set_flex_flow(cui_dialogeg, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_dialogeg, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(cui_dialogeg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_dialogeg, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_dialogeg, lv_color_hex(0x2E2D2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_dialogeg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_dialogeg, lv_color_hex(0x316671), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_dialogeg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_dialogeg, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_dialogeg, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_dialogeg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_dialogeg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_dialogeg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_dialogeg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_dialogeg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_dialogeg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_dialogtext;
    cui_dialogtext = ui_paneleg_create(cui_dialogeg);
    lv_obj_set_width(cui_dialogtext, lv_pct(100));
    lv_obj_set_height(cui_dialogtext, lv_pct(65));
    lv_obj_set_x(cui_dialogtext, 0);
    lv_obj_set_y(cui_dialogtext, 0);
    lv_obj_set_flex_flow(cui_dialogtext, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_dialogtext, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_row(cui_dialogtext, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_dialogtext, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label;
    cui_Label = lv_label_create(cui_dialogtext);
    lv_obj_set_width(cui_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label, "");
    ui_object_set_themeable_style_property(cui_Label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(cui_Label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(cui_Label, ui_font_WebnarRegular20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(cui_Label, 0);
    lv_obj_t * cui_option;
    cui_option = ui_paneleg_create(cui_dialogeg);
    lv_obj_set_width(cui_option, lv_pct(100));
    lv_obj_set_height(cui_option, lv_pct(36));
    lv_obj_set_x(cui_option, 0);
    lv_obj_set_y(cui_option, 0);
    lv_obj_set_flex_flow(cui_option, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_option, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_row(cui_option, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_option, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_dialogOK;
    cui_dialogOK = ui_rowitem_create(cui_option);
    lv_obj_set_width(cui_dialogOK, lv_pct(50));
    lv_obj_set_height(cui_dialogOK, lv_pct(100));
    lv_obj_set_x(cui_dialogOK, 0);
    lv_obj_set_y(cui_dialogOK, 0);
    lv_obj_set_style_border_color(cui_dialogOK, lv_color_hex(0x316671), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_dialogOK, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_dialogOK, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_dialogOK, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_dialogOK, lv_color_hex(0x2EEEFC), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(cui_dialogOK, 76, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_set_x(ui_comp_get_child(cui_dialogOK, UI_COMP_ROWITEM_LABEL), 0);
    lv_obj_set_y(ui_comp_get_child(cui_dialogOK, UI_COMP_ROWITEM_LABEL), 0);
    lv_obj_set_align(ui_comp_get_child(cui_dialogOK, UI_COMP_ROWITEM_LABEL), LV_ALIGN_CENTER);
    lv_label_set_text(ui_comp_get_child(cui_dialogOK, UI_COMP_ROWITEM_LABEL), "OK");
    lv_obj_set_style_text_font(ui_comp_get_child(cui_dialogOK, UI_COMP_ROWITEM_LABEL), ui_font_WebnarRegular20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_dialogcancel;
    cui_dialogcancel = ui_rowitem_create(cui_option);
    lv_obj_set_width(cui_dialogcancel, lv_pct(50));
    lv_obj_set_height(cui_dialogcancel, lv_pct(100));
    lv_obj_set_x(cui_dialogcancel, 0);
    lv_obj_set_y(cui_dialogcancel, 0);
    lv_obj_set_style_border_color(cui_dialogcancel, lv_color_hex(0x316671), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_dialogcancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_dialogcancel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_dialogcancel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_dialogcancel, lv_color_hex(0x2EEEFC), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(cui_dialogcancel, 76, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_set_x(ui_comp_get_child(cui_dialogcancel, UI_COMP_ROWITEM_LABEL), 0);
    lv_obj_set_y(ui_comp_get_child(cui_dialogcancel, UI_COMP_ROWITEM_LABEL), 0);
    lv_obj_set_align(ui_comp_get_child(cui_dialogcancel, UI_COMP_ROWITEM_LABEL), LV_ALIGN_CENTER);
    lv_label_set_text(ui_comp_get_child(cui_dialogcancel, UI_COMP_ROWITEM_LABEL), "Cancel");
    lv_obj_set_style_text_font(ui_comp_get_child(cui_dialogcancel, UI_COMP_ROWITEM_LABEL), ui_font_WebnarRegular20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_DIALOGEG_NUM);
    children[UI_COMP_DIALOGEG_DIALOGEG] = cui_dialogeg;
    children[UI_COMP_DIALOGEG_DIALOGTEXT] = cui_dialogtext;
    children[UI_COMP_DIALOGEG_DIALOGTEXT_LABEL] = cui_Label;
    children[UI_COMP_DIALOGEG_OPTION] = cui_option;
    children[UI_COMP_DIALOGEG_DIALOGOK] = cui_dialogOK;
    children[UI_COMP_DIALOGEG_DIALOGOK_LABEL] = ui_comp_get_child(cui_dialogOK, UI_COMP_ROWITEM_LABEL);
    children[UI_COMP_DIALOGEG_DIALOGCANCEL] = cui_dialogcancel;
    children[UI_COMP_DIALOGEG_DIALOGCANCEL_LABEL] = ui_comp_get_child(cui_dialogcancel, UI_COMP_ROWITEM_LABEL);
    lv_obj_add_event_cb(cui_dialogeg, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_dialogeg, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_dialogeg_create_hook(cui_dialogeg);
    return cui_dialogeg;
}

