// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_COMP_ROWITEM_H
#define _UI_COMP_ROWITEM_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT rowitem
#define UI_COMP_ROWITEM_ROWITEM 0
#define UI_COMP_ROWITEM_LABEL 1
#define _UI_COMP_ROWITEM_NUM 2
lv_obj_t * ui_rowitem_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
