// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

void ui_event_comp_rowswitch_switch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    lv_obj_t ** comp_rowswitch = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_basic_set_property(comp_rowswitch[UI_COMP_ROWSWITCH_CONTPILL_SWITCHLABEL], _UI_BASIC_PROPERTY_POSITION_X,  12);
        _ui_label_set_property(comp_rowswitch[UI_COMP_ROWSWITCH_CONTPILL_SWITCHLABEL], _UI_LABEL_PROPERTY_TEXT, "ON");
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_basic_set_property(comp_rowswitch[UI_COMP_ROWSWITCH_CONTPILL_SWITCHLABEL], _UI_BASIC_PROPERTY_POSITION_X,  22);
        _ui_label_set_property(comp_rowswitch[UI_COMP_ROWSWITCH_CONTPILL_SWITCHLABEL], _UI_LABEL_PROPERTY_TEXT, "OFF");
    }
}

// COMPONENT rowswitch

lv_obj_t * ui_rowswitch_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_rowswitch;
    cui_rowswitch = lv_obj_create(comp_parent);
    lv_obj_set_height(cui_rowswitch, 54);
    lv_obj_set_width(cui_rowswitch, lv_pct(100));
    lv_obj_set_align(cui_rowswitch, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_rowswitch, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_rowswitch, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(cui_rowswitch, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_rowswitch, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_rowswitch, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_transparent);
    ui_object_set_themeable_style_property(cui_rowswitch, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_transparent);
    lv_obj_set_style_border_width(cui_rowswitch, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_rowswitch, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_rowswitch, 36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_rowswitch, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_rowswitch, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_rowswitch, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_rowswitch, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_rowswitch, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_menurowbg);
    ui_object_set_themeable_style_property(cui_rowswitch, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_menurowbg);

    lv_obj_t * cui_imgicon;
    cui_imgicon = lv_image_create(cui_rowswitch);
    lv_obj_set_width(cui_imgicon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_imgicon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_imgicon, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_imgicon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_imgicon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_spacer;
    cui_spacer = lv_image_create(cui_rowswitch);
    lv_obj_set_width(cui_spacer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_spacer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_spacer, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_spacer, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_spacer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_contpill;
    cui_contpill = lv_obj_create(cui_rowswitch);
    lv_obj_set_width(cui_contpill, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_contpill, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_contpill, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_contpill, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_contpill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_contpill, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_transparent);
    ui_object_set_themeable_style_property(cui_contpill, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_transparent);
    lv_obj_set_style_border_width(cui_contpill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_contpill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_contpill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_contpill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_contpill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_switch;
    cui_switch = lv_switch_create(cui_contpill);
    lv_obj_set_width(cui_switch, 54);
    lv_obj_set_height(cui_switch, 22);
    lv_obj_set_align(cui_switch, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(cui_switch, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_switch, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_switch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_switch, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_switch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_switch, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_switch, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_switch, 16, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(cui_switch, lv_color_hex(0x2EEEFC), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(cui_switch, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(cui_switch, lv_color_hex(0x317170), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(cui_switch, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(cui_switch, 1, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_side(cui_switch, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_set_style_radius(cui_switch, 16, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_switch, lv_color_hex(0xC9C9C9), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_switch, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_switch, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_switch, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_switch, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_switch, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_switch, 16, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(cui_switch, lv_color_hex(0x2EEEFC), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(cui_switch, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(cui_switch, lv_color_hex(0x317170), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(cui_switch, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(cui_switch, 1, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_side(cui_switch, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_radius(cui_switch, 16, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_switch, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_switch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_switch, lv_color_hex(0xE2E6F5), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_switch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_switch, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_switch, LV_BORDER_SIDE_FULL, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_switch, 16, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(cui_switch, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(cui_switch, 255, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(cui_switch, lv_color_hex(0xE2E6F5), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(cui_switch, 255, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(cui_switch, 1, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_border_side(cui_switch, LV_BORDER_SIDE_FULL, LV_PART_KNOB | LV_STATE_CHECKED);

    lv_obj_t * cui_switchlabel;
    cui_switchlabel = lv_label_create(cui_contpill);
    lv_obj_set_width(cui_switchlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_switchlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_switchlabel, 22);
    lv_obj_set_y(cui_switchlabel, -1);
    lv_obj_set_align(cui_switchlabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_switchlabel, "OFF");
    lv_obj_set_style_text_color(cui_switchlabel, lv_color_hex(0xF2F4FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_switchlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_switchlabel, &ui_font_WebnarSemiBold12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_ROWSWITCH_NUM);
    children[UI_COMP_ROWSWITCH_ROWSWITCH] = cui_rowswitch;
    children[UI_COMP_ROWSWITCH_IMGICON] = cui_imgicon;
    children[UI_COMP_ROWSWITCH_SPACER] = cui_spacer;
    children[UI_COMP_ROWSWITCH_CONTPILL] = cui_contpill;
    children[UI_COMP_ROWSWITCH_CONTPILL_SWITCH] = cui_switch;
    children[UI_COMP_ROWSWITCH_CONTPILL_SWITCHLABEL] = cui_switchlabel;
    lv_obj_add_event_cb(cui_rowswitch, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_rowswitch, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_switch, ui_event_comp_rowswitch_switch, LV_EVENT_ALL, children);
    ui_comp_rowswitch_create_hook(cui_rowswitch);
    return cui_rowswitch;
}

