// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_COMP_BTN_H
#define _UI_COMP_BTN_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT BTN
#define UI_COMP_BTN_BTN  0
#define UI_COMP_BTN_BTNL 1
#define _UI_COMP_BTN_NUM 2
lv_obj_t* ui_BTN_create(lv_obj_t* comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
