// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT cmptablerow4col

lv_obj_t * ui_cmptablerow4col_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_cmptablerow4col;
    cui_cmptablerow4col = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_cmptablerow4col, 976);
    lv_obj_set_height(cui_cmptablerow4col, 52);
    lv_obj_remove_flag(cui_cmptablerow4col, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_cmptablerow4col, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_cmptablerow4col, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_transparent);
    ui_object_set_themeable_style_property(cui_cmptablerow4col, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_transparent);
    lv_obj_set_style_border_width(cui_cmptablerow4col, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_cmptablerow4col, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_cmptablerow4col, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_cmptablerow4col, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_cmptablerow4col, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_labname;
    cui_labname = ui_cmpfocuscell_create(cui_cmptablerow4col);
    lv_obj_set_width(cui_labname, 360);
    lv_obj_set_height(cui_labname, 52);
    lv_obj_set_x(cui_labname, 0);
    lv_obj_set_y(cui_labname, 0);
    lv_obj_set_style_radius(cui_labname, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_labname, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_transparent);
    ui_object_set_themeable_style_property(cui_labname, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_transparent);
    lv_obj_set_style_border_width(cui_labname, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_label_set_text(ui_comp_get_child(cui_labname, UI_COMP_CMPFOCUSCELL_LABEL), "xxxxx.jpg");
    lv_obj_set_style_text_font(ui_comp_get_child(cui_labname, UI_COMP_CMPFOCUSCELL_LABEL), &ui_font_WebnarRegular18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_labsize;
    cui_labsize = ui_cmpfocuscell_create(cui_cmptablerow4col);
    lv_obj_set_width(cui_labsize, 140);
    lv_obj_set_height(cui_labsize, 52);
    lv_obj_set_x(cui_labsize, 360);
    lv_obj_set_y(cui_labsize, 0);
    lv_obj_set_style_radius(cui_labsize, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_labsize, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_transparent);
    ui_object_set_themeable_style_property(cui_labsize, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_transparent);
    lv_obj_set_style_border_width(cui_labsize, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_label_set_text(ui_comp_get_child(cui_labsize, UI_COMP_CMPFOCUSCELL_LABEL), "1.6MG");
    lv_obj_set_style_text_font(ui_comp_get_child(cui_labsize, UI_COMP_CMPFOCUSCELL_LABEL), &ui_font_WebnarRegular18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_labtype;
    cui_labtype = ui_cmpfocuscell_create(cui_cmptablerow4col);
    lv_obj_set_width(cui_labtype, 150);
    lv_obj_set_height(cui_labtype, 52);
    lv_obj_set_x(cui_labtype, 500);
    lv_obj_set_y(cui_labtype, 0);
    lv_obj_set_style_radius(cui_labtype, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_labtype, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_transparent);
    ui_object_set_themeable_style_property(cui_labtype, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_transparent);
    lv_obj_set_style_border_width(cui_labtype, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_label_set_text(ui_comp_get_child(cui_labtype, UI_COMP_CMPFOCUSCELL_LABEL), "Photo");
    lv_obj_set_style_text_font(ui_comp_get_child(cui_labtype, UI_COMP_CMPFOCUSCELL_LABEL), &ui_font_WebnarRegular18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_labdate;
    cui_labdate = ui_cmpfocuscell_create(cui_cmptablerow4col);
    lv_obj_set_width(cui_labdate, 326);
    lv_obj_set_height(cui_labdate, 52);
    lv_obj_set_x(cui_labdate, 650);
    lv_obj_set_y(cui_labdate, 0);
    lv_obj_set_style_radius(cui_labdate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_labdate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_transparent);
    ui_object_set_themeable_style_property(cui_labdate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_transparent);
    lv_obj_set_style_border_width(cui_labdate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_label_set_text(ui_comp_get_child(cui_labdate, UI_COMP_CMPFOCUSCELL_LABEL), "2025-08-26 10:00");
    lv_obj_set_style_text_font(ui_comp_get_child(cui_labdate, UI_COMP_CMPFOCUSCELL_LABEL), &ui_font_WebnarRegular18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_CMPTABLEROW4COL_NUM);
    children[UI_COMP_CMPTABLEROW4COL_CMPTABLEROW4COL] = cui_cmptablerow4col;
    children[UI_COMP_CMPTABLEROW4COL_LABNAME] = cui_labname;
    children[UI_COMP_CMPTABLEROW4COL_LABNAME_LABEL] = ui_comp_get_child(cui_labname, UI_COMP_CMPFOCUSCELL_LABEL);
    children[UI_COMP_CMPTABLEROW4COL_LABSIZE] = cui_labsize;
    children[UI_COMP_CMPTABLEROW4COL_LABSIZE_LABEL] = ui_comp_get_child(cui_labsize, UI_COMP_CMPFOCUSCELL_LABEL);
    children[UI_COMP_CMPTABLEROW4COL_LABTYPE] = cui_labtype;
    children[UI_COMP_CMPTABLEROW4COL_LABTYPE_LABEL] = ui_comp_get_child(cui_labtype, UI_COMP_CMPFOCUSCELL_LABEL);
    children[UI_COMP_CMPTABLEROW4COL_LABDATE] = cui_labdate;
    children[UI_COMP_CMPTABLEROW4COL_LABDATE_LABEL] = ui_comp_get_child(cui_labdate, UI_COMP_CMPFOCUSCELL_LABEL);
    lv_obj_add_event_cb(cui_cmptablerow4col, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_cmptablerow4col, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_cmptablerow4col_create_hook(cui_cmptablerow4col);
    return cui_cmptablerow4col;
}

