// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT distance

lv_obj_t * ui_distance_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_distance;
    cui_distance = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_distance, 306);
    lv_obj_set_height(cui_distance, 133);
    lv_obj_set_x(cui_distance, 400);
    lv_obj_set_y(cui_distance, 130);
    lv_obj_set_flex_flow(cui_distance, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_distance, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(cui_distance, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_distance, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_distance, lv_color_hex(0x2E2D2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_distance, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_distance, lv_color_hex(0x316671), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_distance, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_distance, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_distance, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_distance, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_distance, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_distance, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_distance, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_distance, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_distance, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_distanceinput;
    cui_distanceinput = ui_paneleg_create(cui_distance);
    lv_obj_set_width(cui_distanceinput, lv_pct(100));
    lv_obj_set_height(cui_distanceinput, lv_pct(65));
    lv_obj_set_x(cui_distanceinput, 0);
    lv_obj_set_y(cui_distanceinput, 0);
    lv_obj_set_flex_flow(cui_distanceinput, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_distanceinput, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_row(cui_distanceinput, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_distanceinput, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_value1;
    cui_value1 = ui_num_create(cui_distanceinput);
    lv_obj_set_x(cui_value1, 0);
    lv_obj_set_y(cui_value1, 0);

    lv_obj_t * cui_value2;
    cui_value2 = ui_num_create(cui_distanceinput);
    lv_obj_set_x(cui_value2, 0);
    lv_obj_set_y(cui_value2, 0);

    lv_obj_t * cui_value3;
    cui_value3 = ui_num_create(cui_distanceinput);
    lv_obj_set_x(cui_value3, 0);
    lv_obj_set_y(cui_value3, 0);

    lv_obj_t * cui_value4;
    cui_value4 = ui_num_create(cui_distanceinput);
    lv_obj_set_x(cui_value4, 0);
    lv_obj_set_y(cui_value4, 0);

    lv_obj_t * cui_distanceopt;
    cui_distanceopt = ui_paneleg_create(cui_distance);
    lv_obj_set_width(cui_distanceopt, lv_pct(100));
    lv_obj_set_height(cui_distanceopt, lv_pct(36));
    lv_obj_set_x(cui_distanceopt, 0);
    lv_obj_set_y(cui_distanceopt, 0);
    lv_obj_set_flex_flow(cui_distanceopt, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_distanceopt, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_row(cui_distanceopt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_distanceopt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_distanceok;
    cui_distanceok = ui_rowitem_create(cui_distanceopt);
    lv_obj_set_width(cui_distanceok, lv_pct(50));
    lv_obj_set_height(cui_distanceok, lv_pct(100));
    lv_obj_set_x(cui_distanceok, 0);
    lv_obj_set_y(cui_distanceok, 0);
    lv_obj_set_style_border_color(cui_distanceok, lv_color_hex(0x316671), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_distanceok, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_distanceok, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_distanceok, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_distanceok, lv_color_hex(0x2EEEFC), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(cui_distanceok, 76, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_set_x(ui_comp_get_child(cui_distanceok, UI_COMP_ROWITEM_LABEL), 0);
    lv_obj_set_y(ui_comp_get_child(cui_distanceok, UI_COMP_ROWITEM_LABEL), 0);
    lv_obj_set_align(ui_comp_get_child(cui_distanceok, UI_COMP_ROWITEM_LABEL), LV_ALIGN_CENTER);
    lv_label_set_text(ui_comp_get_child(cui_distanceok, UI_COMP_ROWITEM_LABEL), "OK");
    lv_obj_set_style_text_font(ui_comp_get_child(cui_distanceok, UI_COMP_ROWITEM_LABEL), ui_font_WebnarRegular20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_distancecancel;
    cui_distancecancel = ui_rowitem_create(cui_distanceopt);
    lv_obj_set_width(cui_distancecancel, lv_pct(50));
    lv_obj_set_height(cui_distancecancel, lv_pct(100));
    lv_obj_set_x(cui_distancecancel, 0);
    lv_obj_set_y(cui_distancecancel, 0);
    lv_obj_set_style_border_color(cui_distancecancel, lv_color_hex(0x316671), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_distancecancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_distancecancel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_distancecancel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_distancecancel, lv_color_hex(0x2EEEFC), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(cui_distancecancel, 76, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_set_x(ui_comp_get_child(cui_distancecancel, UI_COMP_ROWITEM_LABEL), 0);
    lv_obj_set_y(ui_comp_get_child(cui_distancecancel, UI_COMP_ROWITEM_LABEL), 0);
    lv_obj_set_align(ui_comp_get_child(cui_distancecancel, UI_COMP_ROWITEM_LABEL), LV_ALIGN_CENTER);
    lv_label_set_text(ui_comp_get_child(cui_distancecancel, UI_COMP_ROWITEM_LABEL), "Cancel");
    lv_obj_set_style_text_font(ui_comp_get_child(cui_distancecancel, UI_COMP_ROWITEM_LABEL), ui_font_WebnarRegular20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_DISTANCE_NUM);
    children[UI_COMP_DISTANCE_DISTANCE] = cui_distance;
    children[UI_COMP_DISTANCE_DISTANCEINPUT] = cui_distanceinput;
    children[UI_COMP_DISTANCE_VALUE1] = cui_value1;
    children[UI_COMP_DISTANCE_VALUE1_IMAGEUP] = ui_comp_get_child(cui_value1, UI_COMP_NUM_IMAGEUP);
    children[UI_COMP_DISTANCE_VALUE1_PANELNUM] = ui_comp_get_child(cui_value1, UI_COMP_NUM_PANELNUM);
    children[UI_COMP_DISTANCE_VALUE1_PANELNUM_LABEL] = ui_comp_get_child(cui_value1, UI_COMP_NUM_PANELNUM_LABEL);
    children[UI_COMP_DISTANCE_VALUE1_IMAGEDOWN] = ui_comp_get_child(cui_value1, UI_COMP_NUM_IMAGEDOWN);
    children[UI_COMP_DISTANCE_VALUE2] = cui_value2;
    children[UI_COMP_DISTANCE_VALUE2_IMAGEUP] = ui_comp_get_child(cui_value2, UI_COMP_NUM_IMAGEUP);
    children[UI_COMP_DISTANCE_VALUE2_PANELNUM] = ui_comp_get_child(cui_value2, UI_COMP_NUM_PANELNUM);
    children[UI_COMP_DISTANCE_VALUE2_PANELNUM_LABEL] = ui_comp_get_child(cui_value2, UI_COMP_NUM_PANELNUM_LABEL);
    children[UI_COMP_DISTANCE_VALUE2_IMAGEDOWN] = ui_comp_get_child(cui_value2, UI_COMP_NUM_IMAGEDOWN);
    children[UI_COMP_DISTANCE_VALUE3] = cui_value3;
    children[UI_COMP_DISTANCE_VALUE3_IMAGEUP] = ui_comp_get_child(cui_value3, UI_COMP_NUM_IMAGEUP);
    children[UI_COMP_DISTANCE_VALUE3_PANELNUM] = ui_comp_get_child(cui_value3, UI_COMP_NUM_PANELNUM);
    children[UI_COMP_DISTANCE_VALUE3_PANELNUM_LABEL] = ui_comp_get_child(cui_value3, UI_COMP_NUM_PANELNUM_LABEL);
    children[UI_COMP_DISTANCE_VALUE3_IMAGEDOWN] = ui_comp_get_child(cui_value3, UI_COMP_NUM_IMAGEDOWN);
    children[UI_COMP_DISTANCE_VALUE4] = cui_value4;
    children[UI_COMP_DISTANCE_VALUE4_IMAGEUP] = ui_comp_get_child(cui_value4, UI_COMP_NUM_IMAGEUP);
    children[UI_COMP_DISTANCE_VALUE4_PANELNUM] = ui_comp_get_child(cui_value4, UI_COMP_NUM_PANELNUM);
    children[UI_COMP_DISTANCE_VALUE4_PANELNUM_LABEL] = ui_comp_get_child(cui_value4, UI_COMP_NUM_PANELNUM_LABEL);
    children[UI_COMP_DISTANCE_VALUE4_IMAGEDOWN] = ui_comp_get_child(cui_value4, UI_COMP_NUM_IMAGEDOWN);
    children[UI_COMP_DISTANCE_DISTANCEOPT] = cui_distanceopt;
    children[UI_COMP_DISTANCE_DISTANCEOK] = cui_distanceok;
    children[UI_COMP_DISTANCE_DISTANCEOK_LABEL] = ui_comp_get_child(cui_distanceok, UI_COMP_ROWITEM_LABEL);
    children[UI_COMP_DISTANCE_DISTANCECANCEL] = cui_distancecancel;
    children[UI_COMP_DISTANCE_DISTANCECANCEL_LABEL] = ui_comp_get_child(cui_distancecancel, UI_COMP_ROWITEM_LABEL);
    lv_obj_add_event_cb(cui_distance, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_distance, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_distance_create_hook(cui_distance);
    return cui_distance;
}

