// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_COMP_DIALOGEG_H
#define _UI_COMP_DIALOGEG_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT dialogeg
#define UI_COMP_DIALOGEG_DIALOGEG 0
#define UI_COMP_DIALOGEG_DIALOGTEXT 1
#define UI_COMP_DIALOGEG_DIALOGTEXT_LABEL 2
#define UI_COMP_DIALOGEG_OPTION 3
#define UI_COMP_DIALOGEG_DIALOGOK 4
#define UI_COMP_DIALOGEG_DIALOGOK_LABEL 5
#define UI_COMP_DIALOGEG_DIALOGCANCEL 6
#define UI_COMP_DIALOGEG_DIALOGCANCEL_LABEL 7
#define _UI_COMP_DIALOGEG_NUM 8
lv_obj_t * ui_dialogeg_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
