// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT distancelabel

lv_obj_t * ui_distancelabel_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_distancelabel;
    cui_distancelabel = lv_obj_create(comp_parent);
    lv_obj_set_height(cui_distancelabel, 54);
    lv_obj_set_width(cui_distancelabel, lv_pct(100));
    lv_obj_set_align(cui_distancelabel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_distancelabel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_distancelabel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(cui_distancelabel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_distancelabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_distancelabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_transparent);
    ui_object_set_themeable_style_property(cui_distancelabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_transparent);
    lv_obj_set_style_border_width(cui_distancelabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_distancelabel, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_distancelabel, 36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_distancelabel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_distancelabel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_distancelabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_distancelabel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_distancelabel, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(cui_distancelabel, 76, LV_PART_MAIN | LV_STATE_FOCUSED);

    /* 距离条目状态约定：
 * - LV_STATE_USER_2：该枪型的“优先距离(Primacy)”条目（每枪型唯一）。
 * - LV_STATE_USER_1：距离条目正在被编辑（临时态）。
 *   编辑结束只清 USER_1；若该条同时是优先距离，则会自然回到 USER_2 样式。
 * - dots 图标：所有距离条目都显示，不用于区分优先距离。
 */
lv_obj_set_style_bg_color(cui_distancelabel, lv_color_hex(0x2EEEFC), LV_PART_MAIN | LV_STATE_USER_1);
lv_obj_set_style_bg_opa(cui_distancelabel, 76, LV_PART_MAIN | LV_STATE_USER_1);

/* 编辑态（USER_1）：无论是否为优先距离，编辑时都显示同样的编辑高亮 */
lv_obj_set_style_bg_color(cui_distancelabel, lv_color_hex(0xFFE08A), LV_PART_MAIN | LV_STATE_USER_2);
lv_obj_set_style_bg_opa(cui_distancelabel, 110, LV_PART_MAIN | LV_STATE_USER_2);

/* 同时满足 USER_1|USER_2 时：以“编辑态”为准（覆盖 USER_2） */
lv_obj_set_style_bg_color(cui_distancelabel, lv_color_hex(0xFFE08A), LV_PART_MAIN | (LV_STATE_USER_1 | LV_STATE_USER_2));
lv_obj_set_style_bg_opa(cui_distancelabel, 110, LV_PART_MAIN | (LV_STATE_USER_1 | LV_STATE_USER_2));
lv_obj_t * cui_contpill;
    cui_contpill = lv_obj_create(cui_distancelabel);
    lv_obj_set_width(cui_contpill, 34);
    lv_obj_set_height(cui_contpill, 34);
    lv_obj_set_align(cui_contpill, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_contpill, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_contpill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_contpill, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_transparent);
    ui_object_set_themeable_style_property(cui_contpill, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_transparent);
    lv_obj_set_style_border_width(cui_contpill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_contpill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_contpill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_contpill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_contpill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_itemlabel;
    cui_itemlabel = lv_label_create(cui_contpill);
    lv_obj_set_width(cui_itemlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_itemlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_itemlabel, LV_ALIGN_CENTER);
    lv_label_set_text(cui_itemlabel, "");
    ui_object_set_themeable_style_property(cui_itemlabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(cui_itemlabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(cui_itemlabel, ui_font_WebnarMedium15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_imgicon;
    cui_imgicon = lv_image_create(cui_distancelabel);
    lv_image_set_src(cui_imgicon, IMAGES_PATH "Dots.png");
    lv_obj_set_width(cui_imgicon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_imgicon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_imgicon, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_imgicon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_imgicon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_spacer;
    cui_spacer = lv_image_create(cui_distancelabel);
    lv_image_set_src(cui_spacer, IMAGES_PATH "Enter2.png");
    lv_obj_set_width(cui_spacer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_spacer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_spacer, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_spacer, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_spacer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_DISTANCELABEL_NUM);
    children[UI_COMP_DISTANCELABEL_DISTANCELABEL] = cui_distancelabel;
    children[UI_COMP_DISTANCELABEL_CONTPILL] = cui_contpill;
    children[UI_COMP_DISTANCELABEL_CONTPILL_ITEMLABEL] = cui_itemlabel;
    children[UI_COMP_DISTANCELABEL_IMGICON] = cui_imgicon;
    children[UI_COMP_DISTANCELABEL_SPACER] = cui_spacer;
    lv_obj_add_event_cb(cui_distancelabel, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_distancelabel, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_distancelabel_create_hook(cui_distancelabel);
    return cui_distancelabel;
}

