// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT cmpdatetimebar

lv_obj_t * ui_cmpdatetimebar_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_cmpdatetimebar;
    cui_cmpdatetimebar = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_cmpdatetimebar, 366);
    lv_obj_set_height(cui_cmpdatetimebar, 44);
    lv_obj_remove_flag(cui_cmpdatetimebar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_cmpdatetimebar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_cmpdatetimebar, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_transparent);
    ui_object_set_themeable_style_property(cui_cmpdatetimebar, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_transparent);
    lv_obj_set_style_border_width(cui_cmpdatetimebar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_cmpdatetimebar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_cmpdatetimebar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_cmpdatetimebar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_cmpdatetimebar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_cellyear;
    cui_cellyear = ui_cmpfocuscell_create(cui_cmpdatetimebar);
    lv_obj_set_width(cui_cellyear, 70);
    lv_obj_set_height(cui_cellyear, 44);
    lv_obj_set_x(cui_cellyear, 0);
    lv_obj_set_y(cui_cellyear, 0);

    lv_label_set_text(ui_comp_get_child(cui_cellyear, UI_COMP_CMPFOCUSCELL_LABEL), "2025");
    lv_obj_set_style_text_font(ui_comp_get_child(cui_cellyear, UI_COMP_CMPFOCUSCELL_LABEL), &ui_font_WebnarRegular15,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_labdash1;
    cui_labdash1 = lv_label_create(cui_cmpdatetimebar);
    lv_obj_set_width(cui_labdash1, 12);
    lv_obj_set_height(cui_labdash1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_labdash1, 78);
    lv_obj_set_y(cui_labdash1, 0);
    lv_obj_set_align(cui_labdash1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_labdash1, "-");
    ui_object_set_themeable_style_property(cui_labdash1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(cui_labdash1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(cui_labdash1, &ui_font_WebnarRegular13, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_cellmonth;
    cui_cellmonth = ui_cmpfocuscell_create(cui_cmpdatetimebar);
    lv_obj_set_width(cui_cellmonth, 48);
    lv_obj_set_height(cui_cellmonth, 44);
    lv_obj_set_x(cui_cellmonth, 98);
    lv_obj_set_y(cui_cellmonth, 0);

    lv_label_set_text(ui_comp_get_child(cui_cellmonth, UI_COMP_CMPFOCUSCELL_LABEL), "12");

    lv_obj_t * cui_labdash2;
    cui_labdash2 = lv_label_create(cui_cmpdatetimebar);
    lv_obj_set_width(cui_labdash2, 12);
    lv_obj_set_height(cui_labdash2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_labdash2, 154);
    lv_obj_set_y(cui_labdash2, 0);
    lv_obj_set_align(cui_labdash2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_labdash2, "-");
    ui_object_set_themeable_style_property(cui_labdash2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(cui_labdash2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(cui_labdash2, &ui_font_WebnarRegular13, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_cellday;
    cui_cellday = ui_cmpfocuscell_create(cui_cmpdatetimebar);
    lv_obj_set_width(cui_cellday, 48);
    lv_obj_set_height(cui_cellday, 44);
    lv_obj_set_x(cui_cellday, 174);
    lv_obj_set_y(cui_cellday, 0);

    lv_label_set_text(ui_comp_get_child(cui_cellday, UI_COMP_CMPFOCUSCELL_LABEL), "30");

    lv_obj_t * cui_cellhour;
    cui_cellhour = ui_cmpfocuscell_create(cui_cmpdatetimebar);
    lv_obj_set_width(cui_cellhour, 48);
    lv_obj_set_height(cui_cellhour, 44);
    lv_obj_set_x(cui_cellhour, 242);
    lv_obj_set_y(cui_cellhour, 0);

    lv_label_set_text(ui_comp_get_child(cui_cellhour, UI_COMP_CMPFOCUSCELL_LABEL), "12");

    lv_obj_t * cui_labcolon;
    cui_labcolon = lv_label_create(cui_cmpdatetimebar);
    lv_obj_set_width(cui_labcolon, 12);
    lv_obj_set_height(cui_labcolon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_labcolon, 298);
    lv_obj_set_y(cui_labcolon, 0);
    lv_obj_set_align(cui_labcolon, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_labcolon, ":");
    ui_object_set_themeable_style_property(cui_labcolon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(cui_labcolon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(cui_labcolon, &ui_font_WebnarRegular13, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_cmpfocuscell1;
    cui_cmpfocuscell1 = ui_cmpfocuscell_create(cui_cmpdatetimebar);
    lv_obj_set_width(cui_cmpfocuscell1, 48);
    lv_obj_set_height(cui_cmpfocuscell1, 44);
    lv_obj_set_x(cui_cmpfocuscell1, 318);
    lv_obj_set_y(cui_cmpfocuscell1, 0);

    lv_label_set_text(ui_comp_get_child(cui_cmpfocuscell1, UI_COMP_CMPFOCUSCELL_LABEL), "00");

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_CMPDATETIMEBAR_NUM);
    children[UI_COMP_CMPDATETIMEBAR_CMPDATETIMEBAR] = cui_cmpdatetimebar;
    children[UI_COMP_CMPDATETIMEBAR_CELLYEAR] = cui_cellyear;
    children[UI_COMP_CMPDATETIMEBAR_CELLYEAR_LABEL] = ui_comp_get_child(cui_cellyear, UI_COMP_CMPFOCUSCELL_LABEL);
    children[UI_COMP_CMPDATETIMEBAR_LABDASH1] = cui_labdash1;
    children[UI_COMP_CMPDATETIMEBAR_CELLMONTH] = cui_cellmonth;
    children[UI_COMP_CMPDATETIMEBAR_CELLMONTH_LABEL] = ui_comp_get_child(cui_cellmonth, UI_COMP_CMPFOCUSCELL_LABEL);
    children[UI_COMP_CMPDATETIMEBAR_LABDASH2] = cui_labdash2;
    children[UI_COMP_CMPDATETIMEBAR_CELLDAY] = cui_cellday;
    children[UI_COMP_CMPDATETIMEBAR_CELLDAY_LABEL] = ui_comp_get_child(cui_cellday, UI_COMP_CMPFOCUSCELL_LABEL);
    children[UI_COMP_CMPDATETIMEBAR_CELLHOUR] = cui_cellhour;
    children[UI_COMP_CMPDATETIMEBAR_CELLHOUR_LABEL] = ui_comp_get_child(cui_cellhour, UI_COMP_CMPFOCUSCELL_LABEL);
    children[UI_COMP_CMPDATETIMEBAR_LABCOLON] = cui_labcolon;
    children[UI_COMP_CMPDATETIMEBAR_CMPFOCUSCELL1] = cui_cmpfocuscell1;
    children[UI_COMP_CMPDATETIMEBAR_CMPFOCUSCELL1_LABEL] = ui_comp_get_child(cui_cmpfocuscell1, UI_COMP_CMPFOCUSCELL_LABEL);
    lv_obj_add_event_cb(cui_cmpdatetimebar, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_cmpdatetimebar, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_cmpdatetimebar_create_hook(cui_cmpdatetimebar);
    return cui_cmpdatetimebar;
}

