// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT LISTLABEL

lv_obj_t *
ui_LISTLABEL_create(lv_obj_t * comp_parent)
{
    lv_obj_t * cui_LISTLABEL;
    cui_LISTLABEL = lv_label_create(comp_parent);
    lv_obj_set_width(cui_LISTLABEL, LV_SIZE_CONTENT); /// 1
    lv_obj_set_height(cui_LISTLABEL, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(cui_LISTLABEL, LV_ALIGN_CENTER);
    lv_label_set_text(cui_LISTLABEL, "");
    ui_object_set_themeable_style_property(cui_LISTLABEL,
                                           LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(cui_LISTLABEL,
                                           LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(cui_LISTLABEL, ui_font_WebnarRegular13, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_LISTLABEL_NUM);
    children[UI_COMP_LISTLABEL_LISTLABEL] = cui_LISTLABEL;
    lv_obj_add_event_cb(cui_LISTLABEL, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_LISTLABEL, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_LISTLABEL_create_hook(cui_LISTLABEL);
    return cui_LISTLABEL;
}
