// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_COMP_CMPTABLEROW4COL_H
#define _UI_COMP_CMPTABLEROW4COL_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT cmptablerow4col
#define UI_COMP_CMPTABLEROW4COL_CMPTABLEROW4COL 0
#define UI_COMP_CMPTABLEROW4COL_LABNAME 1
#define UI_COMP_CMPTABLEROW4COL_LABNAME_LABEL 2
#define UI_COMP_CMPTABLEROW4COL_LABSIZE 3
#define UI_COMP_CMPTABLEROW4COL_LABSIZE_LABEL 4
#define UI_COMP_CMPTABLEROW4COL_LABTYPE 5
#define UI_COMP_CMPTABLEROW4COL_LABTYPE_LABEL 6
#define UI_COMP_CMPTABLEROW4COL_LABDATE 7
#define UI_COMP_CMPTABLEROW4COL_LABDATE_LABEL 8
#define _UI_COMP_CMPTABLEROW4COL_NUM 9
lv_obj_t * ui_cmptablerow4col_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
