// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_COMP_DATEITEM_H
#define _UI_COMP_DATEITEM_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT DateItem
#define UI_COMP_DATEITEM_DATEITEM 0
#define UI_COMP_DATEITEM_ADD      1
#define UI_COMP_DATEITEM_NUM      2
#define UI_COMP_DATEITEM_SUB      3
#define _UI_COMP_DATEITEM_NUM     4
lv_obj_t* ui_DateItem_create(lv_obj_t* comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
