// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_COMP_DIV__H
#define _UI_COMP_DIV__H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT div_
#define UI_COMP_DIV__DIV_ 0
#define _UI_COMP_DIV__NUM 1
lv_obj_t * ui_div__create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
