// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_COMP_NUM_H
#define _UI_COMP_NUM_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT num
#define UI_COMP_NUM_NUM 0
#define UI_COMP_NUM_IMAGEUP 1
#define UI_COMP_NUM_PANELNUM 2
#define UI_COMP_NUM_PANELNUM_LABEL 3
#define UI_COMP_NUM_IMAGEDOWN 4
#define _UI_COMP_NUM_NUM 5
lv_obj_t * ui_num_create(lv_obj_t * comp_parent);
void ui_event_comp_num_num(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
