// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT cmptableheader

lv_obj_t * ui_cmptableheader_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_cmptableheader;
    cui_cmptableheader = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_cmptableheader, 976);
    lv_obj_set_height(cui_cmptableheader, 44);
    lv_obj_set_x(cui_cmptableheader, 18);
    lv_obj_set_y(cui_cmptableheader, 0);
    lv_obj_remove_flag(cui_cmptableheader, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_cmptableheader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_cmptableheader, lv_color_hex(0x122128), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_cmptableheader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_cmptableheader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_cmptableheader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_cmptableheader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_cmptableheader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_cmptableheader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_labhdrname;
    cui_labhdrname = ui_cmpfocuscell_create(cui_cmptableheader);
    lv_obj_set_width(cui_labhdrname, 360);
    lv_obj_set_height(cui_labhdrname, 44);
    lv_obj_set_x(cui_labhdrname, 0);
    lv_obj_set_y(cui_labhdrname, 0);
    lv_obj_set_style_radius(cui_labhdrname, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_labhdrname, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_transparent);
    ui_object_set_themeable_style_property(cui_labhdrname, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_transparent);
    lv_obj_set_style_border_width(cui_labhdrname, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_label_set_text(ui_comp_get_child(cui_labhdrname, UI_COMP_CMPFOCUSCELL_LABEL), "File Name");
    lv_obj_set_style_text_font(ui_comp_get_child(cui_labhdrname, UI_COMP_CMPFOCUSCELL_LABEL), &ui_font_WebnarMedium18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_labhdrsize;
    cui_labhdrsize = ui_cmpfocuscell_create(cui_cmptableheader);
    lv_obj_set_width(cui_labhdrsize, 140);
    lv_obj_set_height(cui_labhdrsize, 44);
    lv_obj_set_x(cui_labhdrsize, 360);
    lv_obj_set_y(cui_labhdrsize, 0);
    lv_obj_set_style_radius(cui_labhdrsize, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_labhdrsize, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_transparent);
    ui_object_set_themeable_style_property(cui_labhdrsize, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_transparent);
    lv_obj_set_style_border_width(cui_labhdrsize, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_label_set_text(ui_comp_get_child(cui_labhdrsize, UI_COMP_CMPFOCUSCELL_LABEL), "File Size");
    lv_obj_set_style_text_font(ui_comp_get_child(cui_labhdrsize, UI_COMP_CMPFOCUSCELL_LABEL), &ui_font_WebnarMedium18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_labhdrtype;
    cui_labhdrtype = ui_cmpfocuscell_create(cui_cmptableheader);
    lv_obj_set_width(cui_labhdrtype, 150);
    lv_obj_set_height(cui_labhdrtype, 44);
    lv_obj_set_x(cui_labhdrtype, 500);
    lv_obj_set_y(cui_labhdrtype, 0);
    lv_obj_set_style_radius(cui_labhdrtype, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_labhdrtype, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_transparent);
    ui_object_set_themeable_style_property(cui_labhdrtype, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_transparent);
    lv_obj_set_style_border_width(cui_labhdrtype, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_label_set_text(ui_comp_get_child(cui_labhdrtype, UI_COMP_CMPFOCUSCELL_LABEL), "Type");
    lv_obj_set_style_text_font(ui_comp_get_child(cui_labhdrtype, UI_COMP_CMPFOCUSCELL_LABEL), &ui_font_WebnarMedium18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_labhdrdate;
    cui_labhdrdate = ui_cmpfocuscell_create(cui_cmptableheader);
    lv_obj_set_width(cui_labhdrdate, 326);
    lv_obj_set_height(cui_labhdrdate, 44);
    lv_obj_set_x(cui_labhdrdate, 650);
    lv_obj_set_y(cui_labhdrdate, 0);
    lv_obj_set_style_radius(cui_labhdrdate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_labhdrdate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_transparent);
    ui_object_set_themeable_style_property(cui_labhdrdate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_transparent);
    lv_obj_set_style_border_width(cui_labhdrdate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_label_set_text(ui_comp_get_child(cui_labhdrdate, UI_COMP_CMPFOCUSCELL_LABEL), "Date Created");
    lv_obj_set_style_text_font(ui_comp_get_child(cui_labhdrdate, UI_COMP_CMPFOCUSCELL_LABEL), &ui_font_WebnarMedium18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_CMPTABLEHEADER_NUM);
    children[UI_COMP_CMPTABLEHEADER_CMPTABLEHEADER] = cui_cmptableheader;
    children[UI_COMP_CMPTABLEHEADER_LABHDRNAME] = cui_labhdrname;
    children[UI_COMP_CMPTABLEHEADER_LABHDRNAME_LABEL] = ui_comp_get_child(cui_labhdrname, UI_COMP_CMPFOCUSCELL_LABEL);
    children[UI_COMP_CMPTABLEHEADER_LABHDRSIZE] = cui_labhdrsize;
    children[UI_COMP_CMPTABLEHEADER_LABHDRSIZE_LABEL] = ui_comp_get_child(cui_labhdrsize, UI_COMP_CMPFOCUSCELL_LABEL);
    children[UI_COMP_CMPTABLEHEADER_LABHDRTYPE] = cui_labhdrtype;
    children[UI_COMP_CMPTABLEHEADER_LABHDRTYPE_LABEL] = ui_comp_get_child(cui_labhdrtype, UI_COMP_CMPFOCUSCELL_LABEL);
    children[UI_COMP_CMPTABLEHEADER_LABHDRDATE] = cui_labhdrdate;
    children[UI_COMP_CMPTABLEHEADER_LABHDRDATE_LABEL] = ui_comp_get_child(cui_labhdrdate, UI_COMP_CMPFOCUSCELL_LABEL);
    lv_obj_add_event_cb(cui_cmptableheader, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_cmptableheader, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_cmptableheader_create_hook(cui_cmptableheader);
    return cui_cmptableheader;
}

