// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT div_

lv_obj_t * ui_div__create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_div_;
    cui_div_ = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_div_, 976);
    lv_obj_set_height(cui_div_, 1);
    lv_obj_remove_flag(cui_div_, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_div_, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_div_, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_transparent);
    ui_object_set_themeable_style_property(cui_div_, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_transparent);
    lv_obj_set_style_border_color(cui_div_, lv_color_hex(0x316671), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_div_, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_div_, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_DIV__NUM);
    children[UI_COMP_DIV__DIV_] = cui_div_;
    lv_obj_add_event_cb(cui_div_, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_div_, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_div__create_hook(cui_div_);
    return cui_div_;
}

