// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

void ui_event_comp_num_num(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_num = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_ENTER) {
        _ui_flag_modify(comp_num[UI_COMP_NUM_IMAGEUP], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(comp_num[UI_COMP_NUM_IMAGEDOWN], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

// COMPONENT num

lv_obj_t * ui_num_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_num;
    cui_num = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_num, 36);
    lv_obj_set_height(cui_num, 60);
    lv_obj_remove_flag(cui_num, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_num, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_num, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_transparent);
    ui_object_set_themeable_style_property(cui_num, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_transparent);
    lv_obj_set_style_border_width(cui_num, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_num, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_num, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_num, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_num, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_num, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_num, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Imageup;
    cui_Imageup = lv_image_create(cui_num);
    lv_image_set_src(cui_Imageup, &ui_img_img_imageup_png);
    lv_obj_set_width(cui_Imageup, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Imageup, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Imageup, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(cui_Imageup, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_Imageup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_panelnum;
    cui_panelnum = ui_paneleg_create(cui_num);
    lv_obj_set_width(cui_panelnum, 36);
    lv_obj_set_height(cui_panelnum, 38);
    lv_obj_set_x(cui_panelnum, 0);
    lv_obj_set_y(cui_panelnum, 0);
    lv_obj_set_align(cui_panelnum, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(cui_panelnum, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_panelnum, lv_color_hex(0x122128), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_panelnum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_panelnum, lv_color_hex(0x316671), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_panelnum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_panelnum, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_panelnum, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_panelnum, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(cui_panelnum, lv_color_hex(0x2EEEFC), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(cui_panelnum, 76, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(cui_panelnum, lv_color_hex(0x316671), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(cui_panelnum, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(cui_panelnum, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_side(cui_panelnum, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_t * cui_Label;
    cui_Label = lv_label_create(cui_panelnum);
    lv_obj_set_width(cui_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label, "1");
    ui_object_set_themeable_style_property(cui_Label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(cui_Label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(cui_Label, &ui_font_WebnarRegular20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(cui_Label, 0);
    lv_obj_t * cui_Imagedown;
    cui_Imagedown = lv_image_create(cui_num);
    lv_image_set_src(cui_Imagedown, &ui_img_img_imagedown_png);
    lv_obj_set_width(cui_Imagedown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Imagedown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Imagedown, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(cui_Imagedown, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_Imagedown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_NUM_NUM);
    children[UI_COMP_NUM_NUM] = cui_num;
    children[UI_COMP_NUM_IMAGEUP] = cui_Imageup;
    children[UI_COMP_NUM_PANELNUM] = cui_panelnum;
    children[UI_COMP_NUM_PANELNUM_LABEL] = cui_Label;
    children[UI_COMP_NUM_IMAGEDOWN] = cui_Imagedown;
    lv_obj_add_event_cb(cui_num, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_num, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_num, ui_event_comp_num_num, LV_EVENT_ALL, children);
    ui_comp_num_create_hook(cui_num);
    return cui_num;
}

