// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_COMP_DISTANCELABEL_H
#define _UI_COMP_DISTANCELABEL_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT distancelabel
#define UI_COMP_DISTANCELABEL_DISTANCELABEL 0
#define UI_COMP_DISTANCELABEL_CONTPILL 1
#define UI_COMP_DISTANCELABEL_CONTPILL_ITEMLABEL 2
#define UI_COMP_DISTANCELABEL_IMGICON 3
#define UI_COMP_DISTANCELABEL_SPACER 4
#define _UI_COMP_DISTANCELABEL_NUM 5
lv_obj_t * ui_distancelabel_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
