// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_COMP_ROWSWITCH_H
#define _UI_COMP_ROWSWITCH_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT rowswitch
#define UI_COMP_ROWSWITCH_ROWSWITCH 0
#define UI_COMP_ROWSWITCH_IMGICON 1
#define UI_COMP_ROWSWITCH_SPACER 2
#define UI_COMP_ROWSWITCH_CONTPILL 3
#define UI_COMP_ROWSWITCH_CONTPILL_SWITCH 4
#define UI_COMP_ROWSWITCH_CONTPILL_SWITCHLABEL 5
#define _UI_COMP_ROWSWITCH_NUM 6
lv_obj_t * ui_rowswitch_create(lv_obj_t * comp_parent);
void ui_event_comp_rowswitch_switch(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
