// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT rowlabel

lv_obj_t * ui_rowlabel_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_rowlabel;
    cui_rowlabel = lv_obj_create(comp_parent);
    lv_obj_set_height(cui_rowlabel, 54);
    lv_obj_set_width(cui_rowlabel, lv_pct(100));
    lv_obj_set_align(cui_rowlabel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_rowlabel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_rowlabel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(cui_rowlabel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_rowlabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_rowlabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_transparent);
    ui_object_set_themeable_style_property(cui_rowlabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_transparent);
    lv_obj_set_style_border_width(cui_rowlabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_rowlabel, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_rowlabel, 36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_rowlabel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_rowlabel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_rowlabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_rowlabel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_rowlabel, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_menurowbg);
    ui_object_set_themeable_style_property(cui_rowlabel, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_menurowbg);

    lv_obj_t * cui_imgicon1;
    cui_imgicon1 = lv_image_create(cui_rowlabel);
    lv_obj_set_width(cui_imgicon1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_imgicon1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_imgicon1, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_imgicon1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_imgicon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_spacer1;
    cui_spacer1 = lv_image_create(cui_rowlabel);
    lv_obj_set_width(cui_spacer1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_spacer1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_spacer1, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_spacer1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_spacer1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_contpill1;
    cui_contpill1 = lv_obj_create(cui_rowlabel);
    lv_obj_set_width(cui_contpill1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_contpill1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_contpill1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_contpill1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_contpill1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_contpill1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_transparent);
    ui_object_set_themeable_style_property(cui_contpill1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_transparent);
    lv_obj_set_style_border_width(cui_contpill1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_contpill1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_contpill1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_contpill1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_contpill1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_itemlabel1;
    cui_itemlabel1 = lv_label_create(cui_contpill1);
    lv_obj_set_width(cui_itemlabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_itemlabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_itemlabel1, LV_ALIGN_CENTER);
    lv_label_set_text(cui_itemlabel1, "");
    ui_object_set_themeable_style_property(cui_itemlabel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(cui_itemlabel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(cui_itemlabel1, &ui_font_WebnarMedium15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_ROWLABEL_NUM);
    children[UI_COMP_ROWLABEL_ROWLABEL] = cui_rowlabel;
    children[UI_COMP_ROWLABEL_IMGICON1] = cui_imgicon1;
    children[UI_COMP_ROWLABEL_SPACER1] = cui_spacer1;
    children[UI_COMP_ROWLABEL_CONTPILL1] = cui_contpill1;
    children[UI_COMP_ROWLABEL_CONTPILL1_ITEMLABEL1] = cui_itemlabel1;
    lv_obj_add_event_cb(cui_rowlabel, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_rowlabel, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_rowlabel_create_hook(cui_rowlabel);
    return cui_rowlabel;
}

