// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT rowenter

lv_obj_t * ui_rowenter_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_rowenter;
    cui_rowenter = lv_obj_create(comp_parent);
    lv_obj_set_height(cui_rowenter, 54);
    lv_obj_set_width(cui_rowenter, lv_pct(100));
    lv_obj_set_align(cui_rowenter, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_rowenter, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_rowenter, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(cui_rowenter, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_rowenter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_rowenter, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_transparent);
    ui_object_set_themeable_style_property(cui_rowenter, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_transparent);
    lv_obj_set_style_border_width(cui_rowenter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_rowenter, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_rowenter, 36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_rowenter, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_rowenter, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_rowenter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_rowenter, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_rowenter, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_menurowbg);
    ui_object_set_themeable_style_property(cui_rowenter, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_menurowbg);

    lv_obj_t * cui_imgicon;
    cui_imgicon = lv_image_create(cui_rowenter);
    lv_obj_set_width(cui_imgicon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_imgicon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_imgicon, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_imgicon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_imgicon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_spacer;
    cui_spacer = lv_image_create(cui_rowenter);
    lv_obj_set_width(cui_spacer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_spacer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_spacer, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_spacer, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_spacer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_contpill;
    cui_contpill = lv_obj_create(cui_rowenter);
    lv_obj_set_width(cui_contpill, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_contpill, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_contpill, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_contpill, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_contpill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_contpill, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_transparent);
    ui_object_set_themeable_style_property(cui_contpill, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_transparent);
    lv_obj_set_style_border_width(cui_contpill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_contpill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_contpill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_contpill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_contpill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Image;
    cui_Image = lv_image_create(cui_contpill);
    lv_obj_set_width(cui_Image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Image, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_ROWENTER_NUM);
    children[UI_COMP_ROWENTER_ROWENTER] = cui_rowenter;
    children[UI_COMP_ROWENTER_IMGICON] = cui_imgicon;
    children[UI_COMP_ROWENTER_SPACER] = cui_spacer;
    children[UI_COMP_ROWENTER_CONTPILL] = cui_contpill;
    children[UI_COMP_ROWENTER_CONTPILL_IMAGE] = cui_Image;
    lv_obj_add_event_cb(cui_rowenter, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_rowenter, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_rowenter_create_hook(cui_rowenter);
    return cui_rowenter;
}

