// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT cmpfocuscell

lv_obj_t * ui_cmpfocuscell_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_cmpfocuscell;
    cui_cmpfocuscell = lv_obj_create(comp_parent);
    lv_obj_set_height(cui_cmpfocuscell, 44);
    lv_obj_set_width(cui_cmpfocuscell, LV_SIZE_CONTENT);   /// 1
    lv_obj_remove_flag(cui_cmpfocuscell, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_cmpfocuscell, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_cmpfocuscell, lv_color_hex(0x122128), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_cmpfocuscell, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_cmpfocuscell, lv_color_hex(0x316671), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_cmpfocuscell, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_cmpfocuscell, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_cmpfocuscell, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_cmpfocuscell, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_cmpfocuscell, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_cmpfocuscell, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_cmpfocuscell, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_cmpfocuscell, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(cui_cmpfocuscell, lv_color_hex(0x122128), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(cui_cmpfocuscell, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(cui_cmpfocuscell, lv_color_hex(0x2EEEFC), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(cui_cmpfocuscell, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(cui_cmpfocuscell, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_side(cui_cmpfocuscell, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_t * cui_Label;
    cui_Label = lv_label_create(cui_cmpfocuscell);
    lv_obj_set_width(cui_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label, "Text");
    ui_object_set_themeable_style_property(cui_Label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(cui_Label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_CMPFOCUSCELL_NUM);
    children[UI_COMP_CMPFOCUSCELL_CMPFOCUSCELL] = cui_cmpfocuscell;
    children[UI_COMP_CMPFOCUSCELL_LABEL] = cui_Label;
    lv_obj_add_event_cb(cui_cmpfocuscell, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_cmpfocuscell, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_cmpfocuscell_create_hook(cui_cmpfocuscell);
    return cui_cmpfocuscell;
}

