// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT cmpmodetoggle

lv_obj_t * ui_cmpmodetoggle_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_cmpmodetoggle;
    cui_cmpmodetoggle = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_cmpmodetoggle, 332);
    lv_obj_set_height(cui_cmpmodetoggle, 44);
    lv_obj_remove_flag(cui_cmpmodetoggle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_cmpmodetoggle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_cmpmodetoggle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_transparent);
    ui_object_set_themeable_style_property(cui_cmpmodetoggle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_transparent);
    lv_obj_set_style_border_width(cui_cmpmodetoggle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_cmpmodetoggle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_cmpmodetoggle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_cmpmodetoggle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_cmpmodetoggle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_cellpreview;
    cui_cellpreview = ui_cmpfocuscell_create(cui_cmpmodetoggle);
    lv_obj_set_width(cui_cellpreview, 160);
    lv_obj_set_height(cui_cellpreview, 44);
    lv_obj_set_x(cui_cellpreview, 0);
    lv_obj_set_y(cui_cellpreview, 0);

    lv_label_set_text(ui_comp_get_child(cui_cellpreview, UI_COMP_CMPFOCUSCELL_LABEL), "Preview Mode");
    lv_obj_set_style_text_font(ui_comp_get_child(cui_cellpreview, UI_COMP_CMPFOCUSCELL_LABEL), &ui_font_WebnarRegular20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_celldelete;
    cui_celldelete = ui_cmpfocuscell_create(cui_cmpmodetoggle);
    lv_obj_set_width(cui_celldelete, 160);
    lv_obj_set_height(cui_celldelete, 44);
    lv_obj_set_x(cui_celldelete, 172);
    lv_obj_set_y(cui_celldelete, 0);

    lv_label_set_text(ui_comp_get_child(cui_celldelete, UI_COMP_CMPFOCUSCELL_LABEL), "Delete Mode");

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_CMPMODETOGGLE_NUM);
    children[UI_COMP_CMPMODETOGGLE_CMPMODETOGGLE] = cui_cmpmodetoggle;
    children[UI_COMP_CMPMODETOGGLE_CELLPREVIEW] = cui_cellpreview;
    children[UI_COMP_CMPMODETOGGLE_CELLPREVIEW_LABEL] = ui_comp_get_child(cui_cellpreview, UI_COMP_CMPFOCUSCELL_LABEL);
    children[UI_COMP_CMPMODETOGGLE_CELLDELETE] = cui_celldelete;
    children[UI_COMP_CMPMODETOGGLE_CELLDELETE_LABEL] = ui_comp_get_child(cui_celldelete, UI_COMP_CMPFOCUSCELL_LABEL);
    lv_obj_add_event_cb(cui_cmpmodetoggle, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_cmpmodetoggle, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_cmpmodetoggle_create_hook(cui_cmpmodetoggle);
    return cui_cmpmodetoggle;
}

