// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT rowitem

lv_obj_t * ui_rowitem_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_rowitem;
    cui_rowitem = lv_obj_create(comp_parent);
    lv_obj_set_height(cui_rowitem, 41);
    lv_obj_set_width(cui_rowitem, lv_pct(100));
    lv_obj_remove_flag(cui_rowitem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_rowitem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_rowitem, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_transparent);
    ui_object_set_themeable_style_property(cui_rowitem, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_transparent);
    lv_obj_set_style_border_width(cui_rowitem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_rowitem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_rowitem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_rowitem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_rowitem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_rowitem, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(cui_rowitem, 76, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(cui_rowitem, lv_color_hex(0x2EEEFC), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(cui_rowitem, 76, LV_PART_MAIN | LV_STATE_USER_1);

    lv_obj_t * cui_Label;
    cui_Label = lv_label_create(cui_rowitem);
    lv_obj_set_width(cui_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label, 16);
    lv_obj_set_y(cui_Label, 0);
    lv_obj_set_align(cui_Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_Label, "White Hot");
    ui_object_set_themeable_style_property(cui_Label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(cui_Label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(cui_Label, &ui_font_WebnarMedium15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_ROWITEM_NUM);
    children[UI_COMP_ROWITEM_ROWITEM] = cui_rowitem;
    children[UI_COMP_ROWITEM_LABEL] = cui_Label;
    lv_obj_add_event_cb(cui_rowitem, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_rowitem, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_rowitem_create_hook(cui_rowitem);
    return cui_rowitem;
}

