// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_COMP_LISTLABEL_H
#define _UI_COMP_LISTLABEL_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT LISTLABEL
#define UI_COMP_LISTLABEL_LISTLABEL 0
#define _UI_COMP_LISTLABEL_NUM      1
lv_obj_t* ui_LISTLABEL_create(lv_obj_t* comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
