// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

void ui_comp_paneleg_create_hook(lv_obj_t * comp)
{
}

void ui_comp_rowtemplate_create_hook(lv_obj_t * comp)
{
}

void ui_comp_rowswitch_create_hook(lv_obj_t * comp)
{
}

void ui_comp_rowlabel_create_hook(lv_obj_t * comp)
{
}

void ui_comp_rowenter_create_hook(lv_obj_t * comp)
{
}
