// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_COMP_ROWITEM1_H
#define _UI_COMP_ROWITEM1_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT rowitem1
#define UI_COMP_ROWITEM1_ROWITEM1 0
#define UI_COMP_ROWITEM1_IMAGELEFT 1
#define UI_COMP_ROWITEM1_LABEL 2
#define UI_COMP_ROWITEM1_IMAGERIGHT 3
#define _UI_COMP_ROWITEM1_NUM 4
lv_obj_t * ui_rowitem1_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
