// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT DateItem

lv_obj_t *
ui_DateItem_create(lv_obj_t * comp_parent)
{
    lv_obj_t * cui_DateItem;
    cui_DateItem = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_DateItem, LV_SIZE_CONTENT); /// 1
    lv_obj_set_height(cui_DateItem, 45); /// 1
    lv_obj_set_align(cui_DateItem, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_DateItem, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_DateItem, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(cui_DateItem, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(cui_DateItem, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_DateItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_DateItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_DateItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_DateItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_DateItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_DateItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_DateItem, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_DateItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_add;
    cui_add = lv_image_create(cui_DateItem);
    lv_image_set_src(cui_add, IMAGES_PATH "imageup.png");
    lv_obj_set_width(cui_add, LV_SIZE_CONTENT); /// 1
    lv_obj_set_height(cui_add, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(cui_add, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_add, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE); /// Flags
    lv_obj_remove_flag(cui_add, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    lv_obj_t * cui_num;
    cui_num = lv_label_create(cui_DateItem);
    lv_obj_set_width(cui_num, 40); /// 1
    lv_obj_set_height(cui_num, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(cui_num, LV_ALIGN_CENTER);
    lv_label_set_text(cui_num, "2025");
    ui_object_set_themeable_style_property(cui_num,
                                           LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(cui_num,
                                           LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_color(cui_num, lv_color_hex(0x37F6FA), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(cui_num, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_align(cui_num, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_num, ui_font_WebnarRegular15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_num, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(cui_num, lv_color_hex(0x2E2D2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_num, 153, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_num, lv_color_hex(0x2E2D2F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(cui_num, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(cui_num, lv_color_hex(0x708383), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_num, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_num, lv_color_hex(0x37F6FA), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(cui_num, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_set_style_border_width(cui_num, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_num, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_num, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_num, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_num, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_sub;
    cui_sub = lv_image_create(cui_DateItem);
    lv_image_set_src(cui_sub, IMAGES_PATH "imagedown.png");
    lv_obj_set_width(cui_sub, LV_SIZE_CONTENT); /// 1
    lv_obj_set_height(cui_sub, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(cui_sub, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_sub, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE); /// Flags
    lv_obj_remove_flag(cui_sub, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_DATEITEM_NUM);
    children[UI_COMP_DATEITEM_DATEITEM] = cui_DateItem;
    children[UI_COMP_DATEITEM_ADD] = cui_add;
    children[UI_COMP_DATEITEM_NUM] = cui_num;
    children[UI_COMP_DATEITEM_SUB] = cui_sub;
    lv_obj_add_event_cb(cui_DateItem, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_DateItem, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_DateItem_create_hook(cui_DateItem);
    return cui_DateItem;
}