// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_COMP_ROWLABEL_H
#define _UI_COMP_ROWLABEL_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT rowlabel
#define UI_COMP_ROWLABEL_ROWLABEL 0
#define UI_COMP_ROWLABEL_IMGICON1 1
#define UI_COMP_ROWLABEL_SPACER1 2
#define UI_COMP_ROWLABEL_CONTPILL1 3
#define UI_COMP_ROWLABEL_CONTPILL1_ITEMLABEL1 4
#define _UI_COMP_ROWLABEL_NUM 5
lv_obj_t * ui_rowlabel_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
