// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_COMP_CMPDATETIMEBAR_H
#define _UI_COMP_CMPDATETIMEBAR_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT cmpdatetimebar
#define UI_COMP_CMPDATETIMEBAR_CMPDATETIMEBAR 0
#define UI_COMP_CMPDATETIMEBAR_CELLYEAR 1
#define UI_COMP_CMPDATETIMEBAR_CELLYEAR_LABEL 2
#define UI_COMP_CMPDATETIMEBAR_LABDASH1 3
#define UI_COMP_CMPDATETIMEBAR_CELLMONTH 4
#define UI_COMP_CMPDATETIMEBAR_CELLMONTH_LABEL 5
#define UI_COMP_CMPDATETIMEBAR_LABDASH2 6
#define UI_COMP_CMPDATETIMEBAR_CELLDAY 7
#define UI_COMP_CMPDATETIMEBAR_CELLDAY_LABEL 8
#define UI_COMP_CMPDATETIMEBAR_CELLHOUR 9
#define UI_COMP_CMPDATETIMEBAR_CELLHOUR_LABEL 10
#define UI_COMP_CMPDATETIMEBAR_LABCOLON 11
#define UI_COMP_CMPDATETIMEBAR_CMPFOCUSCELL1 12
#define UI_COMP_CMPDATETIMEBAR_CMPFOCUSCELL1_LABEL 13
#define _UI_COMP_CMPDATETIMEBAR_NUM 14
lv_obj_t * ui_cmpdatetimebar_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
