// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_COMP_ROWENTER_H
#define _UI_COMP_ROWENTER_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT rowenter
#define UI_COMP_ROWENTER_ROWENTER 0
#define UI_COMP_ROWENTER_IMGICON 1
#define UI_COMP_ROWENTER_SPACER 2
#define UI_COMP_ROWENTER_CONTPILL 3
#define UI_COMP_ROWENTER_CONTPILL_IMAGE 4
#define _UI_COMP_ROWENTER_NUM 5
lv_obj_t * ui_rowenter_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
