// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT rowitem1

lv_obj_t * ui_rowitem1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_rowitem1;
    cui_rowitem1 = lv_obj_create(comp_parent);
    lv_obj_set_height(cui_rowitem1, 41);
    lv_obj_set_width(cui_rowitem1, lv_pct(100));
    lv_obj_remove_flag(cui_rowitem1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_rowitem1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_rowitem1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_transparent);
    ui_object_set_themeable_style_property(cui_rowitem1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_transparent);
    lv_obj_set_style_border_width(cui_rowitem1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_rowitem1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_rowitem1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_rowitem1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_rowitem1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_rowitem1, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(cui_rowitem1, 76, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(cui_rowitem1, lv_color_hex(0x2EEEFC), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(cui_rowitem1, 76, LV_PART_MAIN | LV_STATE_USER_1);

    lv_obj_t * cui_Imageleft;
    cui_Imageleft = lv_image_create(cui_rowitem1);
    lv_image_set_src(cui_Imageleft, &ui_img_img_left_png);
    lv_obj_set_width(cui_Imageleft, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Imageleft, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Imageleft, 16);
    lv_obj_set_y(cui_Imageleft, 0);
    lv_obj_set_align(cui_Imageleft, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(cui_Imageleft, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_Imageleft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Label;
    cui_Label = lv_label_create(cui_rowitem1);
    lv_obj_set_width(cui_Label, 36);
    lv_obj_set_height(cui_Label, 21);
    lv_obj_set_x(cui_Label, 30);
    lv_obj_set_y(cui_Label, 0);
    lv_obj_set_align(cui_Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_Label, "1");
    ui_object_set_themeable_style_property(cui_Label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(cui_Label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_align(cui_Label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label, &ui_font_WebnarMedium15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Imageright;
    cui_Imageright = lv_image_create(cui_rowitem1);
    lv_image_set_src(cui_Imageright, &ui_img_img_right_png);
    lv_obj_set_width(cui_Imageright, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Imageright, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Imageright, 66);
    lv_obj_set_y(cui_Imageright, 0);
    lv_obj_set_align(cui_Imageright, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(cui_Imageright, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_Imageright, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_ROWITEM1_NUM);
    children[UI_COMP_ROWITEM1_ROWITEM1] = cui_rowitem1;
    children[UI_COMP_ROWITEM1_IMAGELEFT] = cui_Imageleft;
    children[UI_COMP_ROWITEM1_LABEL] = cui_Label;
    children[UI_COMP_ROWITEM1_IMAGERIGHT] = cui_Imageright;
    lv_obj_add_event_cb(cui_rowitem1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_rowitem1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_rowitem1_create_hook(cui_rowitem1);
    return cui_rowitem1;
}

