// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_COMP_CMPTABLEHEADER_H
#define _UI_COMP_CMPTABLEHEADER_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT cmptableheader
#define UI_COMP_CMPTABLEHEADER_CMPTABLEHEADER 0
#define UI_COMP_CMPTABLEHEADER_LABHDRNAME 1
#define UI_COMP_CMPTABLEHEADER_LABHDRNAME_LABEL 2
#define UI_COMP_CMPTABLEHEADER_LABHDRSIZE 3
#define UI_COMP_CMPTABLEHEADER_LABHDRSIZE_LABEL 4
#define UI_COMP_CMPTABLEHEADER_LABHDRTYPE 5
#define UI_COMP_CMPTABLEHEADER_LABHDRTYPE_LABEL 6
#define UI_COMP_CMPTABLEHEADER_LABHDRDATE 7
#define UI_COMP_CMPTABLEHEADER_LABHDRDATE_LABEL 8
#define _UI_COMP_CMPTABLEHEADER_NUM 9
lv_obj_t * ui_cmptableheader_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
