// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT paneleg

lv_obj_t * ui_paneleg_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_paneleg;
    cui_paneleg = lv_obj_create(comp_parent);
    lv_obj_set_height(cui_paneleg, 50);
    lv_obj_set_width(cui_paneleg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(cui_paneleg, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_remove_flag(cui_paneleg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_paneleg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_paneleg, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_transparent);
    ui_object_set_themeable_style_property(cui_paneleg, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_transparent);
    lv_obj_set_style_border_width(cui_paneleg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_paneleg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_paneleg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_paneleg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_paneleg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_PANELEG_NUM);
    children[UI_COMP_PANELEG_PANELEG] = cui_paneleg;
    lv_obj_add_event_cb(cui_paneleg, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_paneleg, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_paneleg_create_hook(cui_paneleg);
    return cui_paneleg;
}

