// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

void
ui_event_comp_BTN_BTN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_BTN = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_FOCUSED) {
        lv_obj_set_style_text_color(comp_BTN[UI_COMP_BTN_BTNL],
                                    lv_color_hex(0x37F6FA),
                                    LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_opa(comp_BTN[UI_COMP_BTN_BTNL], 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        ui_object_set_themeable_style_property(comp_BTN[UI_COMP_BTN_BTNL],
                                               LV_PART_MAIN | LV_STATE_DEFAULT,
                                               LV_STYLE_TEXT_COLOR,
                                               _ui_theme_color_Text);
        ui_object_set_themeable_style_property(comp_BTN[UI_COMP_BTN_BTNL],
                                               LV_PART_MAIN | LV_STATE_DEFAULT,
                                               LV_STYLE_TEXT_OPA,
                                               _ui_theme_alpha_Text);
    }
}

// COMPONENT BTN

lv_obj_t *
ui_BTN_create(lv_obj_t * comp_parent)
{
    lv_obj_t * cui_BTN;
    cui_BTN = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_BTN, 62);
    lv_obj_set_height(cui_BTN, 36);
    lv_obj_set_align(cui_BTN, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_BTN, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(cui_BTN, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_BTN, lv_color_hex(0x122128), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_BTN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_BTN, lv_color_hex(0x708383), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_BTN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_BTN, lv_color_hex(0x37F6FA), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(cui_BTN, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(cui_BTN, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_BTN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_BTN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_BTN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_BTN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_BTNL;
    cui_BTNL = lv_label_create(cui_BTN);
    lv_obj_set_width(cui_BTNL, LV_SIZE_CONTENT); /// 1
    lv_obj_set_height(cui_BTNL, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(cui_BTNL, LV_ALIGN_CENTER);
    lv_label_set_text(cui_BTNL, "ALL");
    ui_object_set_themeable_style_property(cui_BTNL,
                                           LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(cui_BTNL,
                                           LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(cui_BTNL, ui_font_WebnarRegular20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_BTN_NUM);
    children[UI_COMP_BTN_BTN] = cui_BTN;
    children[UI_COMP_BTN_BTNL] = cui_BTNL;
    lv_obj_add_event_cb(cui_BTN, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_BTN, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_BTN, ui_event_comp_BTN_BTN, LV_EVENT_ALL, children);
    ui_comp_BTN_create_hook(cui_BTN);
    return cui_BTN;
}