// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_COMP__H
#define _UI_COMP__H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

void get_component_child_event_cb(lv_event_t * e);
void del_component_child_event_cb(lv_event_t * e);

lv_obj_t * ui_comp_get_child(lv_obj_t * comp, uint32_t child_idx);
extern uint32_t LV_EVENT_GET_COMP_CHILD;
#include "ui_comp_cmpdatetimebar.h"
#include "ui_comp_cmpfocuscell.h"
#include "ui_comp_cmpmodetoggle.h"
#include "ui_comp_cmptableheader.h"
#include "ui_comp_cmptablerow4col.h"
#include "ui_comp_div_.h"
#include "ui_comp_paneleg.h"
#include "ui_comp_rowenter.h"
#include "ui_comp_rowlabel.h"
#include "ui_comp_rowswitch.h"

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
