// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_COMP_CMPMODETOGGLE_H
#define _UI_COMP_CMPMODETOGGLE_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT cmpmodetoggle
#define UI_COMP_CMPMODETOGGLE_CMPMODETOGGLE 0
#define UI_COMP_CMPMODETOGGLE_CELLPREVIEW 1
#define UI_COMP_CMPMODETOGGLE_CELLPREVIEW_LABEL 2
#define UI_COMP_CMPMODETOGGLE_CELLDELETE 3
#define UI_COMP_CMPMODETOGGLE_CELLDELETE_LABEL 4
#define _UI_COMP_CMPMODETOGGLE_NUM 5
lv_obj_t * ui_cmpmodetoggle_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
