// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_MainPage = NULL;
lv_obj_t * ui_contstatusbar = NULL;
lv_obj_t * ui_contstatusitems = NULL;
lv_obj_t * ui_contitemsd = NULL;
lv_obj_t * ui_imgsd = NULL;
lv_obj_t * ui_labelsd = NULL;
lv_obj_t * ui_contitempolarity = NULL;
lv_obj_t * ui_imgpolarity = NULL;
lv_obj_t * ui_contitemgun = NULL;
lv_obj_t * ui_imggun = NULL;
lv_obj_t * ui_contitemzoom = NULL;
lv_obj_t * ui_imgzoom = NULL;
lv_obj_t * ui_labelzoom = NULL;
lv_obj_t * ui_contitemwifi = NULL;
lv_obj_t * ui_imgwifi = NULL;
lv_obj_t * ui_contitemdate = NULL;
lv_obj_t * ui_labeldate = NULL;
lv_obj_t * ui_contitemtime = NULL;
lv_obj_t * ui_labeltime = NULL;
lv_obj_t * ui_contstatusbattery = NULL;
lv_obj_t * ui_imgbattery = NULL;
lv_obj_t * ui_contyaw = NULL;
lv_obj_t * ui_arrowyawimage = NULL;
lv_obj_t * ui_yawscale = NULL;
lv_obj_t * ui_controll = NULL;
lv_obj_t * ui_rollscale = NULL;
lv_obj_t * ui_controlllabel = NULL;
lv_obj_t * ui_rolllabel = NULL;
lv_obj_t * ui_arrowrollimage = NULL;
lv_obj_t * ui_contpitch = NULL;
lv_obj_t * ui_pitchscale = NULL;
lv_obj_t * ui_contpitchlabel = NULL;
lv_obj_t * ui_pitchlabel = NULL;
lv_obj_t * ui_arrowpitchimage = NULL;
lv_obj_t * ui_contdistance = NULL;
lv_obj_t * ui_distancelabel = NULL;
lv_obj_t * ui_contrecord = NULL;
lv_obj_t * ui_recordimage = NULL;
lv_obj_t * ui_recordtime = NULL;
lv_obj_t * ui_recordtimelabel = NULL;
lv_obj_t * ui_contmenu = NULL;
lv_obj_t * ui_lbltitle = NULL;
lv_obj_t * ui_contlistbg = NULL;
lv_obj_t * ui_contpages = NULL;
lv_obj_t * ui_contpage1 = NULL;
lv_obj_t * ui_rowlrf = NULL;
lv_obj_t * ui_rowimagemode = NULL;
lv_obj_t * ui_rowbrightness = NULL;
lv_obj_t * ui_rowcontrast = NULL;
lv_obj_t * ui_rowsharpness = NULL;
lv_obj_t * ui_rowbgreflesh = NULL;
lv_obj_t * ui_rowultraclear = NULL;
lv_obj_t * ui_contpage2 = NULL;
lv_obj_t * ui_rowpip = NULL;
lv_obj_t * ui_rowwifi = NULL;
lv_obj_t * ui_rowtilt = NULL;
lv_obj_t * ui_rowcompass = NULL;
lv_obj_t * ui_rowreticle = NULL;
lv_obj_t * ui_rowballistic = NULL;
lv_obj_t * ui_rowmic = NULL;
lv_obj_t * ui_contpage3 = NULL;
lv_obj_t * ui_rowrav = NULL;
lv_obj_t * ui_rowstandby = NULL;
lv_obj_t * ui_rowcompasscalibration = NULL;
lv_obj_t * ui_rowdeadpixel = NULL;
lv_obj_t * ui_rowstatusbar = NULL;
lv_obj_t * ui_rowdeletefile = NULL;
lv_obj_t * ui_rowsetting = NULL;
// event funtions

// build funtions

void ui_MainPage_screen_init(void)
{
    ui_MainPage = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MainPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_MainPage, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_pagebg);
    ui_object_set_themeable_style_property(ui_MainPage, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_pagebg);

    ui_contstatusbar = ui_paneleg_create(ui_MainPage);
    lv_obj_set_width(ui_contstatusbar, 1024);
    lv_obj_set_height(ui_contstatusbar, 50);
    lv_obj_set_x(ui_contstatusbar, 0);
    lv_obj_set_y(ui_contstatusbar, 0);
    lv_obj_set_align(ui_contstatusbar, LV_ALIGN_BOTTOM_MID);

    ui_contstatusitems = ui_paneleg_create(ui_contstatusbar);
    lv_obj_set_x(ui_contstatusitems, 0);
    lv_obj_set_y(ui_contstatusitems, 0);
    lv_obj_set_flex_flow(ui_contstatusitems, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contstatusitems, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_left(ui_contstatusitems, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_contstatusitems, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_contstatusitems, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_contstatusitems, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_contstatusitems, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_contstatusitems, 24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contitemsd = ui_paneleg_create(ui_contstatusitems);
    lv_obj_set_x(ui_contitemsd, 0);
    lv_obj_set_y(ui_contitemsd, 0);
    lv_obj_set_flex_flow(ui_contitemsd, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contitemsd, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);

    ui_imgsd = lv_image_create(ui_contitemsd);
    lv_image_set_src(ui_imgsd, &ui_img_img_sd_png);
    lv_obj_set_width(ui_imgsd, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgsd, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgsd, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgsd, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgsd, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_move_to_index(ui_imgsd, 0);
    ui_labelsd = lv_label_create(ui_contitemsd);
    lv_obj_set_width(ui_labelsd, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelsd, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelsd, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelsd, "30.1G");
    ui_object_set_themeable_style_property(ui_labelsd, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_labelsd, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_labelsd, &ui_font_WebnarSemiBold24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_labelsd, 1);
    ui_contitempolarity = ui_paneleg_create(ui_contstatusitems);
    lv_obj_set_x(ui_contitempolarity, 0);
    lv_obj_set_y(ui_contitempolarity, 0);

    ui_imgpolarity = lv_image_create(ui_contitempolarity);
    lv_image_set_src(ui_imgpolarity, &ui_img_1590413862);
    lv_obj_set_width(ui_imgpolarity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgpolarity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgpolarity, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgpolarity, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgpolarity, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_move_to_index(ui_imgpolarity, 0);
    ui_contitemgun = ui_paneleg_create(ui_contstatusitems);
    lv_obj_set_x(ui_contitemgun, 0);
    lv_obj_set_y(ui_contitemgun, 0);

    ui_imggun = lv_image_create(ui_contitemgun);
    lv_image_set_src(ui_imggun, &ui_img_img_guntype1_png);
    lv_obj_set_width(ui_imggun, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imggun, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imggun, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imggun, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imggun, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_move_to_index(ui_imggun, 0);
    ui_contitemzoom = ui_paneleg_create(ui_contstatusitems);
    lv_obj_set_x(ui_contitemzoom, 0);
    lv_obj_set_y(ui_contitemzoom, 0);
    lv_obj_set_flex_flow(ui_contitemzoom, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contitemzoom, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);

    ui_imgzoom = lv_image_create(ui_contitemzoom);
    lv_image_set_src(ui_imgzoom, &ui_img_img_enlarge_png);
    lv_obj_set_width(ui_imgzoom, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgzoom, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgzoom, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgzoom, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgzoom, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_move_to_index(ui_imgzoom, 0);
    ui_labelzoom = lv_label_create(ui_contitemzoom);
    lv_obj_set_width(ui_labelzoom, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelzoom, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelzoom, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelzoom, "1X");
    ui_object_set_themeable_style_property(ui_labelzoom, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_labelzoom, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_labelzoom, &ui_font_WebnarSemiBold24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_labelzoom, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_labelzoom, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_labelzoom, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_border_width(ui_labelzoom, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_labelzoom, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_labelzoom, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_labelzoom, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_labelzoom, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_labelzoom, 1);
    ui_contitemwifi = ui_paneleg_create(ui_contstatusitems);
    lv_obj_set_x(ui_contitemwifi, 0);
    lv_obj_set_y(ui_contitemwifi, 0);

    ui_imgwifi = lv_image_create(ui_contitemwifi);
    lv_image_set_src(ui_imgwifi, &ui_img_img_wifi_png);
    lv_obj_set_width(ui_imgwifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgwifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgwifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgwifi, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgwifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_move_to_index(ui_imgwifi, 0);
    ui_contitemdate = ui_paneleg_create(ui_contstatusitems);
    lv_obj_set_x(ui_contitemdate, 0);
    lv_obj_set_y(ui_contitemdate, 0);

    ui_labeldate = lv_label_create(ui_contitemdate);
    lv_obj_set_width(ui_labeldate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labeldate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labeldate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labeldate, "25/06/25");
    ui_object_set_themeable_style_property(ui_labeldate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_labeldate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_labeldate, &ui_font_WebnarSemiBold24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_labeldate, 0);
    ui_contitemtime = ui_paneleg_create(ui_contstatusitems);
    lv_obj_set_x(ui_contitemtime, 0);
    lv_obj_set_y(ui_contitemtime, 0);

    ui_labeltime = lv_label_create(ui_contitemtime);
    lv_obj_set_width(ui_labeltime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labeltime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labeltime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labeltime, "16:00");
    ui_object_set_themeable_style_property(ui_labeltime, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_labeltime, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_labeltime, &ui_font_WebnarSemiBold24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_labeltime, 0);
    ui_contstatusbattery = ui_paneleg_create(ui_contstatusbar);
    lv_obj_set_x(ui_contstatusbattery, -10);
    lv_obj_set_y(ui_contstatusbattery, 0);
    lv_obj_set_align(ui_contstatusbattery, LV_ALIGN_RIGHT_MID);

    ui_imgbattery = lv_image_create(ui_contstatusbattery);
    lv_image_set_src(ui_imgbattery, &ui_img_img_battery1_png);
    lv_obj_set_width(ui_imgbattery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgbattery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgbattery, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_imgbattery, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgbattery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_move_to_index(ui_imgbattery, 0);
    ui_contyaw = ui_paneleg_create(ui_MainPage);
    lv_obj_set_width(ui_contyaw, 222);
    lv_obj_set_height(ui_contyaw, 44);
    lv_obj_set_x(ui_contyaw, 0);
    lv_obj_set_y(ui_contyaw, 0);
    lv_obj_set_align(ui_contyaw, LV_ALIGN_TOP_MID);

    ui_arrowyawimage = lv_image_create(ui_contyaw);
    lv_image_set_src(ui_arrowyawimage, &ui_img_img_arrowyawimage_png);
    lv_obj_set_width(ui_arrowyawimage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_arrowyawimage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_arrowyawimage, 0);
    lv_obj_set_y(ui_arrowyawimage, 2);
    lv_obj_set_align(ui_arrowyawimage, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_arrowyawimage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_arrowyawimage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_move_to_index(ui_arrowyawimage, 0);
    ui_yawscale = ui_paneleg_create(ui_contyaw);
    lv_obj_set_width(ui_yawscale, lv_pct(100));
    lv_obj_set_height(ui_yawscale, lv_pct(100));
    lv_obj_set_x(ui_yawscale, 0);
    lv_obj_set_y(ui_yawscale, 0);
    lv_obj_set_align(ui_yawscale, LV_ALIGN_TOP_LEFT);

    ui_controll = ui_paneleg_create(ui_MainPage);
    lv_obj_set_width(ui_controll, 93);
    lv_obj_set_height(ui_controll, 312);
    lv_obj_set_x(ui_controll, 20);
    lv_obj_set_y(ui_controll, 0);
    lv_obj_set_align(ui_controll, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_controll, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_rollscale = ui_paneleg_create(ui_controll);
    lv_obj_set_width(ui_rollscale, 62);
    lv_obj_set_height(ui_rollscale, 276);
    lv_obj_set_x(ui_rollscale, 0);
    lv_obj_set_y(ui_rollscale, 0);
    lv_obj_set_align(ui_rollscale, LV_ALIGN_TOP_RIGHT);

    ui_controlllabel = ui_paneleg_create(ui_controll);
    lv_obj_set_height(ui_controlllabel, 25);
    lv_obj_set_width(ui_controlllabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_controlllabel, 14);
    lv_obj_set_y(ui_controlllabel, 0);
    lv_obj_set_style_radius(ui_controlllabel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_controlllabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_bg1);
    ui_object_set_themeable_style_property(ui_controlllabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_bg1);
    ui_object_set_themeable_style_property(ui_controlllabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_borders1);
    ui_object_set_themeable_style_property(ui_controlllabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_borders1);
    lv_obj_set_style_border_width(ui_controlllabel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_controlllabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_controlllabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_controlllabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_controlllabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rolllabel = lv_label_create(ui_controlllabel);
    lv_obj_set_width(ui_rolllabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rolllabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_rolllabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rolllabel, "0°");
    ui_object_set_themeable_style_property(ui_rolllabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_rolllabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_rolllabel, &ui_font_WebnarSemiBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_rolllabel, 0);
    ui_arrowrollimage = lv_image_create(ui_controll);
    lv_image_set_src(ui_arrowrollimage, &ui_img_img_arrowrollimage_png);
    lv_obj_set_width(ui_arrowrollimage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_arrowrollimage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_arrowrollimage, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_arrowrollimage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_arrowrollimage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_move_to_index(ui_arrowrollimage, 2);
    ui_contpitch = ui_paneleg_create(ui_MainPage);
    lv_obj_set_width(ui_contpitch, 100);
    lv_obj_set_height(ui_contpitch, 312);
    lv_obj_set_x(ui_contpitch, -20);
    lv_obj_set_y(ui_contpitch, 0);
    lv_obj_set_align(ui_contpitch, LV_ALIGN_RIGHT_MID);

    ui_pitchscale = ui_paneleg_create(ui_contpitch);
    lv_obj_set_height(ui_pitchscale, 278);
    lv_obj_set_width(ui_pitchscale, lv_pct(100));
    lv_obj_set_x(ui_pitchscale, 0);
    lv_obj_set_y(ui_pitchscale, 0);
    lv_obj_set_align(ui_pitchscale, LV_ALIGN_TOP_MID);

    ui_contpitchlabel = ui_paneleg_create(ui_contpitch);
    lv_obj_set_height(ui_contpitchlabel, 25);
    lv_obj_set_width(ui_contpitchlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_contpitchlabel, 0);
    lv_obj_set_y(ui_contpitchlabel, 0);
    lv_obj_set_align(ui_contpitchlabel, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_radius(ui_contpitchlabel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_contpitchlabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_bg1);
    ui_object_set_themeable_style_property(ui_contpitchlabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_bg1);
    ui_object_set_themeable_style_property(ui_contpitchlabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_borders1);
    ui_object_set_themeable_style_property(ui_contpitchlabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_borders1);
    lv_obj_set_style_border_width(ui_contpitchlabel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_contpitchlabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_contpitchlabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_contpitchlabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_contpitchlabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pitchlabel = lv_label_create(ui_contpitchlabel);
    lv_obj_set_width(ui_pitchlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pitchlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_pitchlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pitchlabel, "0°");
    ui_object_set_themeable_style_property(ui_pitchlabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_pitchlabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_pitchlabel, &ui_font_WebnarSemiBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_pitchlabel, 0);
    ui_arrowpitchimage = lv_image_create(ui_contpitch);
    lv_image_set_src(ui_arrowpitchimage, &ui_img_img_arrowpitchimage_png);
    lv_obj_set_width(ui_arrowpitchimage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_arrowpitchimage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_arrowpitchimage, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_arrowpitchimage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_arrowpitchimage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_move_to_index(ui_arrowpitchimage, 2);
    ui_contdistance = ui_paneleg_create(ui_MainPage);
    lv_obj_set_width(ui_contdistance, 76);
    lv_obj_set_height(ui_contdistance, 40);
    lv_obj_set_x(ui_contdistance, 20);
    lv_obj_set_y(ui_contdistance, 10);
    lv_obj_set_align(ui_contdistance, LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_contdistance, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_distancelabel = lv_label_create(ui_contdistance);
    lv_obj_set_width(ui_distancelabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_distancelabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_distancelabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_distancelabel, "1000M");
    ui_object_set_themeable_style_property(ui_distancelabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_distancelabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_distancelabel, &ui_font_WebnarRegular24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_distancelabel, 0);
    ui_contrecord = ui_paneleg_create(ui_MainPage);
    lv_obj_set_x(ui_contrecord, -21);
    lv_obj_set_y(ui_contrecord, 10);
    lv_obj_set_align(ui_contrecord, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_contrecord, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contrecord, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_contrecord, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_pad_row(ui_contrecord, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_contrecord, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_recordimage = lv_image_create(ui_contrecord);
    lv_image_set_src(ui_recordimage, &ui_img_img_record_png);
    lv_obj_set_width(ui_recordimage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_recordimage, LV_SIZE_CONTENT);    /// 1
    lv_obj_add_flag(ui_recordimage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_recordimage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_move_to_index(ui_recordimage, 0);
    ui_recordtime = ui_paneleg_create(ui_contrecord);
    lv_obj_set_width(ui_recordtime, 58);
    lv_obj_set_height(ui_recordtime, 40);
    lv_obj_set_x(ui_recordtime, 0);
    lv_obj_set_y(ui_recordtime, 0);

    ui_recordtimelabel = lv_label_create(ui_recordtime);
    lv_obj_set_width(ui_recordtimelabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_recordtimelabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_recordtimelabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_recordtimelabel, "00:13");
    ui_object_set_themeable_style_property(ui_recordtimelabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_recordtimelabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_recordtimelabel, &ui_font_WebnarRegular24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_recordtimelabel, 0);
    ui_contmenu = ui_paneleg_create(ui_MainPage);
    lv_obj_set_width(ui_contmenu, 180);
    lv_obj_set_height(ui_contmenu, 428);
    lv_obj_set_x(ui_contmenu, 20);
    lv_obj_set_y(ui_contmenu, 77);
    lv_obj_set_align(ui_contmenu, LV_ALIGN_TOP_LEFT);

    ui_lbltitle = lv_label_create(ui_contmenu);
    lv_obj_set_height(ui_lbltitle, 45);
    lv_obj_set_width(ui_lbltitle, LV_SIZE_CONTENT);   /// 1
    lv_label_set_text(ui_lbltitle, "PIP");
    ui_object_set_themeable_style_property(ui_lbltitle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_lbltitle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_lbltitle, &ui_font_WebnarItalic32, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_lbltitle, 0);
    ui_contlistbg = ui_paneleg_create(ui_contmenu);
    lv_obj_set_height(ui_contlistbg, 378);
    lv_obj_set_width(ui_contlistbg, lv_pct(100));
    lv_obj_set_x(ui_contlistbg, 0);
    lv_obj_set_y(ui_contlistbg, 50);
    lv_obj_set_align(ui_contlistbg, LV_ALIGN_TOP_LEFT);
    lv_obj_set_style_radius(ui_contlistbg, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_contlistbg, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_menubg);
    ui_object_set_themeable_style_property(ui_contlistbg, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_menubg);

    ui_contpages = ui_paneleg_create(ui_contlistbg);
    lv_obj_set_width(ui_contpages, lv_pct(100));
    lv_obj_set_height(ui_contpages, lv_pct(100));
    lv_obj_set_x(ui_contpages, 0);
    lv_obj_set_y(ui_contpages, 0);
    lv_obj_set_align(ui_contpages, LV_ALIGN_TOP_LEFT);

    ui_contpage1 = ui_paneleg_create(ui_contpages);
    lv_obj_set_width(ui_contpage1, lv_pct(100));
    lv_obj_set_height(ui_contpage1, lv_pct(100));
    lv_obj_set_x(ui_contpage1, 0);
    lv_obj_set_y(ui_contpage1, 0);
    lv_obj_set_align(ui_contpage1, LV_ALIGN_TOP_LEFT);
    lv_obj_set_flex_flow(ui_contpage1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_contpage1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_contpage1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_pad_row(ui_contpage1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_contpage1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rowlrf = ui_rowswitch_create(ui_contpage1);
    lv_obj_set_x(ui_rowlrf, 0);
    lv_obj_set_y(ui_rowlrf, 0);

    lv_image_set_src(ui_comp_get_child(ui_rowlrf, UI_COMP_ROWSWITCH_IMGICON), &ui_img_img_lrf_png);

    lv_image_set_src(ui_comp_get_child(ui_rowlrf, UI_COMP_ROWSWITCH_SPACER), &ui_img_img_dots_png);

    ui_rowimagemode = ui_rowlabel_create(ui_contpage1);
    lv_obj_set_x(ui_rowimagemode, 0);
    lv_obj_set_y(ui_rowimagemode, 0);

    lv_image_set_src(ui_comp_get_child(ui_rowimagemode, UI_COMP_ROWLABEL_IMGICON1), &ui_img_img_imagemode_png);

    lv_image_set_src(ui_comp_get_child(ui_rowimagemode, UI_COMP_ROWLABEL_SPACER1), &ui_img_img_dots_png);

    lv_label_set_text(ui_comp_get_child(ui_rowimagemode, UI_COMP_ROWLABEL_CONTPILL1_ITEMLABEL1), "White Hot");

    ui_rowbrightness = ui_rowlabel_create(ui_contpage1);
    lv_obj_set_x(ui_rowbrightness, 0);
    lv_obj_set_y(ui_rowbrightness, 0);

    lv_image_set_src(ui_comp_get_child(ui_rowbrightness, UI_COMP_ROWLABEL_IMGICON1), &ui_img_img_brightness_png);

    lv_image_set_src(ui_comp_get_child(ui_rowbrightness, UI_COMP_ROWLABEL_SPACER1), &ui_img_img_dots_png);

    lv_label_set_text(ui_comp_get_child(ui_rowbrightness, UI_COMP_ROWLABEL_CONTPILL1_ITEMLABEL1), "1");

    ui_rowcontrast = ui_rowlabel_create(ui_contpage1);
    lv_obj_set_x(ui_rowcontrast, 0);
    lv_obj_set_y(ui_rowcontrast, 0);

    lv_image_set_src(ui_comp_get_child(ui_rowcontrast, UI_COMP_ROWLABEL_IMGICON1), &ui_img_img_contrast_png);

    lv_image_set_src(ui_comp_get_child(ui_rowcontrast, UI_COMP_ROWLABEL_SPACER1), &ui_img_img_dots_png);

    lv_label_set_text(ui_comp_get_child(ui_rowcontrast, UI_COMP_ROWLABEL_CONTPILL1_ITEMLABEL1), "1");

    ui_rowsharpness = ui_rowlabel_create(ui_contpage1);
    lv_obj_set_x(ui_rowsharpness, 0);
    lv_obj_set_y(ui_rowsharpness, 0);

    lv_image_set_src(ui_comp_get_child(ui_rowsharpness, UI_COMP_ROWLABEL_IMGICON1), &ui_img_img_sharpness_png);

    lv_image_set_src(ui_comp_get_child(ui_rowsharpness, UI_COMP_ROWLABEL_SPACER1), &ui_img_img_dots_png);

    lv_label_set_text(ui_comp_get_child(ui_rowsharpness, UI_COMP_ROWLABEL_CONTPILL1_ITEMLABEL1), "1");

    ui_rowbgreflesh = ui_rowlabel_create(ui_contpage1);
    lv_obj_set_x(ui_rowbgreflesh, 0);
    lv_obj_set_y(ui_rowbgreflesh, 0);

    lv_image_set_src(ui_comp_get_child(ui_rowbgreflesh, UI_COMP_ROWLABEL_IMGICON1), &ui_img_img_backgroundreflesh_png);

    lv_image_set_src(ui_comp_get_child(ui_rowbgreflesh, UI_COMP_ROWLABEL_SPACER1), &ui_img_img_dots_png);

    lv_label_set_text(ui_comp_get_child(ui_rowbgreflesh, UI_COMP_ROWLABEL_CONTPILL1_ITEMLABEL1), "30 HZ");

    ui_rowultraclear = ui_rowswitch_create(ui_contpage1);
    lv_obj_set_x(ui_rowultraclear, 0);
    lv_obj_set_y(ui_rowultraclear, 0);

    lv_image_set_src(ui_comp_get_child(ui_rowultraclear, UI_COMP_ROWSWITCH_IMGICON), &ui_img_img_ultraclear_png);

    lv_image_set_src(ui_comp_get_child(ui_rowultraclear, UI_COMP_ROWSWITCH_SPACER), &ui_img_img_dots_png);

    ui_contpage2 = ui_paneleg_create(ui_contpages);
    lv_obj_set_width(ui_contpage2, lv_pct(100));
    lv_obj_set_height(ui_contpage2, lv_pct(100));
    lv_obj_set_x(ui_contpage2, 0);
    lv_obj_set_y(ui_contpage2, 0);
    lv_obj_set_align(ui_contpage2, LV_ALIGN_TOP_LEFT);
    lv_obj_set_flex_flow(ui_contpage2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_contpage2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_contpage2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_pad_row(ui_contpage2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_contpage2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rowpip = ui_rowswitch_create(ui_contpage2);
    lv_obj_set_x(ui_rowpip, 0);
    lv_obj_set_y(ui_rowpip, 0);

    lv_image_set_src(ui_comp_get_child(ui_rowpip, UI_COMP_ROWSWITCH_IMGICON), &ui_img_img_pip_png);

    lv_image_set_src(ui_comp_get_child(ui_rowpip, UI_COMP_ROWSWITCH_SPACER), &ui_img_img_dots_png);

    ui_rowwifi = ui_rowswitch_create(ui_contpage2);
    lv_obj_set_x(ui_rowwifi, 0);
    lv_obj_set_y(ui_rowwifi, 0);

    lv_image_set_src(ui_comp_get_child(ui_rowwifi, UI_COMP_ROWSWITCH_IMGICON), &ui_img_1583056019);

    lv_image_set_src(ui_comp_get_child(ui_rowwifi, UI_COMP_ROWSWITCH_SPACER), &ui_img_img_dots_png);

    ui_rowtilt = ui_rowswitch_create(ui_contpage2);
    lv_obj_set_x(ui_rowtilt, 0);
    lv_obj_set_y(ui_rowtilt, 0);

    lv_image_set_src(ui_comp_get_child(ui_rowtilt, UI_COMP_ROWSWITCH_IMGICON), &ui_img_img_tilt_png);

    lv_image_set_src(ui_comp_get_child(ui_rowtilt, UI_COMP_ROWSWITCH_SPACER), &ui_img_img_dots_png);

    ui_rowcompass = ui_rowswitch_create(ui_contpage2);
    lv_obj_set_x(ui_rowcompass, 0);
    lv_obj_set_y(ui_rowcompass, 0);

    lv_image_set_src(ui_comp_get_child(ui_rowcompass, UI_COMP_ROWSWITCH_IMGICON), &ui_img_img_compass_png);

    lv_image_set_src(ui_comp_get_child(ui_rowcompass, UI_COMP_ROWSWITCH_SPACER), &ui_img_img_dots_png);

    ui_rowreticle = ui_rowenter_create(ui_contpage2);
    lv_obj_set_x(ui_rowreticle, 0);
    lv_obj_set_y(ui_rowreticle, 0);

    lv_image_set_src(ui_comp_get_child(ui_rowreticle, UI_COMP_ROWENTER_IMGICON), &ui_img_img_reticle_png);

    lv_image_set_src(ui_comp_get_child(ui_rowreticle, UI_COMP_ROWENTER_SPACER), &ui_img_img_dots_png);

    lv_image_set_src(ui_comp_get_child(ui_rowreticle, UI_COMP_ROWENTER_CONTPILL_IMAGE), &ui_img_img_enter2_png);

    ui_rowballistic = ui_rowswitch_create(ui_contpage2);
    lv_obj_set_x(ui_rowballistic, 0);
    lv_obj_set_y(ui_rowballistic, 0);

    lv_image_set_src(ui_comp_get_child(ui_rowballistic, UI_COMP_ROWSWITCH_IMGICON), &ui_img_img_ballistic_png);

    lv_image_set_src(ui_comp_get_child(ui_rowballistic, UI_COMP_ROWSWITCH_SPACER), &ui_img_img_dots_png);

    ui_rowmic = ui_rowswitch_create(ui_contpage2);
    lv_obj_set_x(ui_rowmic, 0);
    lv_obj_set_y(ui_rowmic, 0);

    lv_image_set_src(ui_comp_get_child(ui_rowmic, UI_COMP_ROWSWITCH_IMGICON), &ui_img_img_microphone_png);

    lv_image_set_src(ui_comp_get_child(ui_rowmic, UI_COMP_ROWSWITCH_SPACER), &ui_img_img_dots_png);

    ui_contpage3 = ui_paneleg_create(ui_contpages);
    lv_obj_set_width(ui_contpage3, lv_pct(100));
    lv_obj_set_height(ui_contpage3, lv_pct(100));
    lv_obj_set_x(ui_contpage3, 0);
    lv_obj_set_y(ui_contpage3, 0);
    lv_obj_set_align(ui_contpage3, LV_ALIGN_TOP_LEFT);
    lv_obj_set_flex_flow(ui_contpage3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_contpage3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_row(ui_contpage3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_contpage3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rowrav = ui_rowswitch_create(ui_contpage3);
    lv_obj_set_x(ui_rowrav, 0);
    lv_obj_set_y(ui_rowrav, 0);

    lv_image_set_src(ui_comp_get_child(ui_rowrav, UI_COMP_ROWSWITCH_IMGICON), &ui_img_img_ravrecording_png);

    lv_image_set_src(ui_comp_get_child(ui_rowrav, UI_COMP_ROWSWITCH_SPACER), &ui_img_img_dots_png);

    ui_rowstandby = ui_rowlabel_create(ui_contpage3);
    lv_obj_set_x(ui_rowstandby, 0);
    lv_obj_set_y(ui_rowstandby, 0);

    lv_image_set_src(ui_comp_get_child(ui_rowstandby, UI_COMP_ROWLABEL_IMGICON1), &ui_img_img_standbytimer_png);

    lv_image_set_src(ui_comp_get_child(ui_rowstandby, UI_COMP_ROWLABEL_SPACER1), &ui_img_img_dots_png);

    lv_label_set_text(ui_comp_get_child(ui_rowstandby, UI_COMP_ROWLABEL_CONTPILL1_ITEMLABEL1), "2 minutes");

    ui_rowcompasscalibration = ui_rowlabel_create(ui_contpage3);
    lv_obj_set_x(ui_rowcompasscalibration, 0);
    lv_obj_set_y(ui_rowcompasscalibration, 0);

    lv_image_set_src(ui_comp_get_child(ui_rowcompasscalibration, UI_COMP_ROWLABEL_IMGICON1),
                     &ui_img_img_compasscalibration_png);

    lv_image_set_src(ui_comp_get_child(ui_rowcompasscalibration, UI_COMP_ROWLABEL_SPACER1), &ui_img_img_dots_png);

    lv_label_set_text(ui_comp_get_child(ui_rowcompasscalibration, UI_COMP_ROWLABEL_CONTPILL1_ITEMLABEL1), "Calibration");

    ui_rowdeadpixel = ui_rowlabel_create(ui_contpage3);
    lv_obj_set_x(ui_rowdeadpixel, 0);
    lv_obj_set_y(ui_rowdeadpixel, 0);

    lv_image_set_src(ui_comp_get_child(ui_rowdeadpixel, UI_COMP_ROWLABEL_IMGICON1), &ui_img_img_deadpixelrepair_png);

    lv_image_set_src(ui_comp_get_child(ui_rowdeadpixel, UI_COMP_ROWLABEL_SPACER1), &ui_img_img_dots_png);

    lv_label_set_text(ui_comp_get_child(ui_rowdeadpixel, UI_COMP_ROWLABEL_CONTPILL1_ITEMLABEL1), "Bad Pixel...");

    ui_rowstatusbar = ui_rowswitch_create(ui_contpage3);
    lv_obj_set_x(ui_rowstatusbar, 0);
    lv_obj_set_y(ui_rowstatusbar, 0);

    lv_image_set_src(ui_comp_get_child(ui_rowstatusbar, UI_COMP_ROWSWITCH_IMGICON), &ui_img_img_statusbar_png);

    lv_image_set_src(ui_comp_get_child(ui_rowstatusbar, UI_COMP_ROWSWITCH_SPACER), &ui_img_img_dots_png);

    ui_rowdeletefile = ui_rowenter_create(ui_contpage3);
    lv_obj_set_x(ui_rowdeletefile, 0);
    lv_obj_set_y(ui_rowdeletefile, 0);

    lv_image_set_src(ui_comp_get_child(ui_rowdeletefile, UI_COMP_ROWENTER_IMGICON), &ui_img_img_deletefile_png);

    lv_image_set_src(ui_comp_get_child(ui_rowdeletefile, UI_COMP_ROWENTER_SPACER), &ui_img_img_dots_png);

    lv_image_set_src(ui_comp_get_child(ui_rowdeletefile, UI_COMP_ROWENTER_CONTPILL_IMAGE), &ui_img_img_enter2_png);

    ui_rowsetting = ui_rowenter_create(ui_contpage3);
    lv_obj_set_x(ui_rowsetting, 0);
    lv_obj_set_y(ui_rowsetting, 0);

    lv_image_set_src(ui_comp_get_child(ui_rowsetting, UI_COMP_ROWENTER_IMGICON), &ui_img_img_setting_png);

    lv_image_set_src(ui_comp_get_child(ui_rowsetting, UI_COMP_ROWENTER_SPACER), &ui_img_img_dots_png);

    lv_image_set_src(ui_comp_get_child(ui_rowsetting, UI_COMP_ROWENTER_CONTPILL_IMAGE), &ui_img_img_enter2_png);

}

void ui_MainPage_screen_destroy(void)
{
    if(ui_MainPage) lv_obj_del(ui_MainPage);

    // NULL screen variables
    ui_MainPage = NULL;
    ui_contstatusbar = NULL;
    ui_contstatusitems = NULL;
    ui_contitemsd = NULL;
    ui_imgsd = NULL;
    ui_labelsd = NULL;
    ui_contitempolarity = NULL;
    ui_imgpolarity = NULL;
    ui_contitemgun = NULL;
    ui_imggun = NULL;
    ui_contitemzoom = NULL;
    ui_imgzoom = NULL;
    ui_labelzoom = NULL;
    ui_contitemwifi = NULL;
    ui_imgwifi = NULL;
    ui_contitemdate = NULL;
    ui_labeldate = NULL;
    ui_contitemtime = NULL;
    ui_labeltime = NULL;
    ui_contstatusbattery = NULL;
    ui_imgbattery = NULL;
    ui_contyaw = NULL;
    ui_arrowyawimage = NULL;
    ui_yawscale = NULL;
    ui_controll = NULL;
    ui_rollscale = NULL;
    ui_controlllabel = NULL;
    ui_rolllabel = NULL;
    ui_arrowrollimage = NULL;
    ui_contpitch = NULL;
    ui_pitchscale = NULL;
    ui_contpitchlabel = NULL;
    ui_pitchlabel = NULL;
    ui_arrowpitchimage = NULL;
    ui_contdistance = NULL;
    ui_distancelabel = NULL;
    ui_contrecord = NULL;
    ui_recordimage = NULL;
    ui_recordtime = NULL;
    ui_recordtimelabel = NULL;
    ui_contmenu = NULL;
    ui_lbltitle = NULL;
    ui_contlistbg = NULL;
    ui_contpages = NULL;
    ui_contpage1 = NULL;
    ui_rowlrf = NULL;
    ui_rowimagemode = NULL;
    ui_rowbrightness = NULL;
    ui_rowcontrast = NULL;
    ui_rowsharpness = NULL;
    ui_rowbgreflesh = NULL;
    ui_rowultraclear = NULL;
    ui_contpage2 = NULL;
    ui_rowpip = NULL;
    ui_rowwifi = NULL;
    ui_rowtilt = NULL;
    ui_rowcompass = NULL;
    ui_rowreticle = NULL;
    ui_rowballistic = NULL;
    ui_rowmic = NULL;
    ui_contpage3 = NULL;
    ui_rowrav = NULL;
    ui_rowstandby = NULL;
    ui_rowcompasscalibration = NULL;
    ui_rowdeadpixel = NULL;
    ui_rowstatusbar = NULL;
    ui_rowdeletefile = NULL;
    ui_rowsetting = NULL;

}
