// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_PlayBar = NULL;
lv_obj_t * ui_pplaybar = NULL;
lv_obj_t * ui_iconprev = NULL;
lv_obj_t * ui_iconstop = NULL;
lv_obj_t * ui_iconnext = NULL;
// event funtions

// build funtions

void ui_PlayBar_screen_init(void)
{
    ui_PlayBar = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_PlayBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_PlayBar, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_pagebg);
    ui_object_set_themeable_style_property(ui_PlayBar, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_pagebg);

    ui_pplaybar = ui_paneleg_create(ui_PlayBar);
    lv_obj_set_width(ui_pplaybar, 750);
    lv_obj_set_height(ui_pplaybar, 96);
    lv_obj_set_x(ui_pplaybar, 0);
    lv_obj_set_y(ui_pplaybar, -20);
    lv_obj_set_align(ui_pplaybar, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_radius(ui_pplaybar, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pplaybar, lv_color_hex(0x122128), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pplaybar, 204, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconprev = lv_image_create(ui_pplaybar);
    lv_image_set_src(ui_iconprev, &ui_img_img_img_prev_png);
    lv_obj_set_width(ui_iconprev, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iconprev, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_iconprev, -50);
    lv_obj_set_y(ui_iconprev, 0);
    lv_obj_set_align(ui_iconprev, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconprev, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_iconprev, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_move_to_index(ui_iconprev, 0);
    ui_iconstop = lv_image_create(ui_pplaybar);
    lv_image_set_src(ui_iconstop, &ui_img_img_img_stop_png);
    lv_obj_set_width(ui_iconstop, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iconstop, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_iconstop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconstop, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_iconstop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_move_to_index(ui_iconstop, 1);
    ui_iconnext = lv_image_create(ui_pplaybar);
    lv_image_set_src(ui_iconnext, &ui_img_img_img_next_png);
    lv_obj_set_width(ui_iconnext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iconnext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_iconnext, 50);
    lv_obj_set_y(ui_iconnext, 0);
    lv_obj_set_align(ui_iconnext, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconnext, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_iconnext, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_move_to_index(ui_iconnext, 2);

}

void ui_PlayBar_screen_destroy(void)
{
    if(ui_PlayBar) lv_obj_del(ui_PlayBar);

    // NULL screen variables
    ui_PlayBar = NULL;
    ui_pplaybar = NULL;
    ui_iconprev = NULL;
    ui_iconstop = NULL;
    ui_iconnext = NULL;

}
