// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_PLAYBAR_H
#define UI_PLAYBAR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PlayBar
extern void ui_PlayBar_screen_init(void);
extern void ui_PlayBar_screen_destroy(void);
extern lv_obj_t * ui_PlayBar;
extern lv_obj_t * ui_pplaybar;
extern lv_obj_t * ui_iconprev;
extern lv_obj_t * ui_iconstop;
extern lv_obj_t * ui_iconnext;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

