// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCRFILEMGR_H
#define UI_SCRFILEMGR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScrFileMgr
extern void ui_ScrFileMgr_screen_init(void);
extern void ui_ScrFileMgr_screen_destroy(void);
extern lv_obj_t * ui_ScrFileMgr;
extern lv_obj_t * ui_proot;
extern lv_obj_t * ui_ptopbar;
extern lv_obj_t * ui_pfilter;
extern lv_obj_t * ui_cellall;
extern lv_obj_t * ui_dtfilter;
extern lv_obj_t * ui_cellsearch;
extern lv_obj_t * ui_togglemode;
extern lv_obj_t * ui_header0;
extern lv_obj_t * ui_ptablelist;
extern lv_obj_t * ui_div0;
extern lv_obj_t * ui_row0;
extern lv_obj_t * ui_div1;
extern lv_obj_t * ui_row1;
extern lv_obj_t * ui_div2;
extern lv_obj_t * ui_row2;
extern lv_obj_t * ui_div3;
extern lv_obj_t * ui_row3;
extern lv_obj_t * ui_div4;
extern lv_obj_t * ui_row4;
extern lv_obj_t * ui_div5;
extern lv_obj_t * ui_row5;
extern lv_obj_t * ui_div6;
extern lv_obj_t * ui_row6;
extern lv_obj_t * ui_div7;
extern lv_obj_t * ui_row7;
extern lv_obj_t * ui_div8;
extern lv_obj_t * ui_row8;
extern lv_obj_t * ui_div9;
extern lv_obj_t * ui_row9;
extern lv_obj_t * ui_div10;
extern lv_obj_t * ui_ppaging;
extern lv_obj_t * ui_cellprev;
extern lv_obj_t * ui_ppage;
extern lv_obj_t * ui_cellnext;
extern lv_obj_t * ui_imgarrowup;
extern lv_obj_t * ui_imgarrowdown;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

