// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_ScrFileMgr = NULL;
lv_obj_t * ui_proot = NULL;
lv_obj_t * ui_ptopbar = NULL;
lv_obj_t * ui_pfilter = NULL;
lv_obj_t * ui_cellall = NULL;
lv_obj_t * ui_dtfilter = NULL;
lv_obj_t * ui_cellsearch = NULL;
lv_obj_t * ui_togglemode = NULL;
lv_obj_t * ui_header0 = NULL;
lv_obj_t * ui_ptablelist = NULL;
lv_obj_t * ui_div0 = NULL;
lv_obj_t * ui_row0 = NULL;
lv_obj_t * ui_div1 = NULL;
lv_obj_t * ui_row1 = NULL;
lv_obj_t * ui_div2 = NULL;
lv_obj_t * ui_row2 = NULL;
lv_obj_t * ui_div3 = NULL;
lv_obj_t * ui_row3 = NULL;
lv_obj_t * ui_div4 = NULL;
lv_obj_t * ui_row4 = NULL;
lv_obj_t * ui_div5 = NULL;
lv_obj_t * ui_row5 = NULL;
lv_obj_t * ui_div6 = NULL;
lv_obj_t * ui_row6 = NULL;
lv_obj_t * ui_div7 = NULL;
lv_obj_t * ui_row7 = NULL;
lv_obj_t * ui_div8 = NULL;
lv_obj_t * ui_row8 = NULL;
lv_obj_t * ui_div9 = NULL;
lv_obj_t * ui_row9 = NULL;
lv_obj_t * ui_div10 = NULL;
lv_obj_t * ui_ppaging = NULL;
lv_obj_t * ui_cellprev = NULL;
lv_obj_t * ui_ppage = NULL;
lv_obj_t * ui_cellnext = NULL;
lv_obj_t * ui_imgarrowup = NULL;
lv_obj_t * ui_imgarrowdown = NULL;
// event funtions

// build funtions

void ui_ScrFileMgr_screen_init(void)
{
    ui_ScrFileMgr = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScrFileMgr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScrFileMgr, lv_color_hex(0x2E2D2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrFileMgr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_proot = ui_paneleg_create(ui_ScrFileMgr);
    lv_obj_set_width(ui_proot, 1024);
    lv_obj_set_height(ui_proot, 768);
    lv_obj_set_x(ui_proot, 0);
    lv_obj_set_y(ui_proot, 0);
    lv_obj_set_align(ui_proot, LV_ALIGN_TOP_LEFT);

    ui_ptopbar = ui_paneleg_create(ui_proot);
    lv_obj_set_width(ui_ptopbar, 976);
    lv_obj_set_height(ui_ptopbar, 72);
    lv_obj_set_x(ui_ptopbar, 24);
    lv_obj_set_y(ui_ptopbar, 18);
    lv_obj_set_align(ui_ptopbar, LV_ALIGN_TOP_LEFT);

    ui_pfilter = ui_paneleg_create(ui_ptopbar);
    lv_obj_set_width(ui_pfilter, 640);
    lv_obj_set_height(ui_pfilter, 44);
    lv_obj_set_x(ui_pfilter, 0);
    lv_obj_set_y(ui_pfilter, 14);
    lv_obj_set_align(ui_pfilter, LV_ALIGN_TOP_LEFT);

    ui_cellall = ui_cmpfocuscell_create(ui_pfilter);
    lv_obj_set_width(ui_cellall, 78);
    lv_obj_set_height(ui_cellall, 44);
    lv_obj_set_x(ui_cellall, 0);
    lv_obj_set_y(ui_cellall, 0);

    lv_label_set_text(ui_comp_get_child(ui_cellall, UI_COMP_CMPFOCUSCELL_LABEL), "ALL");
    lv_obj_set_style_text_font(ui_comp_get_child(ui_cellall, UI_COMP_CMPFOCUSCELL_LABEL), &ui_font_WebnarRegular20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dtfilter = ui_cmpdatetimebar_create(ui_pfilter);
    lv_obj_set_x(ui_dtfilter, 88);
    lv_obj_set_y(ui_dtfilter, 0);

    ui_cellsearch = ui_cmpfocuscell_create(ui_pfilter);
    lv_obj_set_width(ui_cellsearch, 92);
    lv_obj_set_height(ui_cellsearch, 44);
    lv_obj_set_x(ui_cellsearch, 464);
    lv_obj_set_y(ui_cellsearch, 0);

    lv_label_set_text(ui_comp_get_child(ui_cellsearch, UI_COMP_CMPFOCUSCELL_LABEL), "Search");
    lv_obj_set_style_text_font(ui_comp_get_child(ui_cellsearch, UI_COMP_CMPFOCUSCELL_LABEL), &ui_font_WebnarRegular20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_togglemode = ui_cmpmodetoggle_create(ui_ptopbar);
    lv_obj_set_x(ui_togglemode, 644);
    lv_obj_set_y(ui_togglemode, 14);

    ui_header0 = ui_cmptableheader_create(ui_proot);
    lv_obj_set_x(ui_header0, 24);
    lv_obj_set_y(ui_header0, 104);

    ui_ptablelist = ui_paneleg_create(ui_proot);
    lv_obj_set_width(ui_ptablelist, 976);
    lv_obj_set_height(ui_ptablelist, LV_SIZE_CONTENT);    /// 516
    lv_obj_set_x(ui_ptablelist, 24);
    lv_obj_set_y(ui_ptablelist, 148);
    lv_obj_set_align(ui_ptablelist, LV_ALIGN_TOP_LEFT);
    lv_obj_set_flex_flow(ui_ptablelist, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ptablelist, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_row(ui_ptablelist, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ptablelist, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_div0 = ui_div__create(ui_ptablelist);
    lv_obj_set_x(ui_div0, 0);
    lv_obj_set_y(ui_div0, 0);

    ui_row0 = ui_cmptablerow4col_create(ui_ptablelist);
    lv_obj_set_width(ui_row0, 976);
    lv_obj_set_height(ui_row0, 52);
    lv_obj_set_x(ui_row0, 0);
    lv_obj_set_y(ui_row0, 0);

    ui_div1 = ui_div__create(ui_ptablelist);
    lv_obj_set_x(ui_div1, 0);
    lv_obj_set_y(ui_div1, 0);

    ui_row1 = ui_cmptablerow4col_create(ui_ptablelist);
    lv_obj_set_width(ui_row1, 976);
    lv_obj_set_height(ui_row1, 52);
    lv_obj_set_x(ui_row1, 0);
    lv_obj_set_y(ui_row1, 0);

    ui_div2 = ui_div__create(ui_ptablelist);
    lv_obj_set_x(ui_div2, 0);
    lv_obj_set_y(ui_div2, 0);

    ui_row2 = ui_cmptablerow4col_create(ui_ptablelist);
    lv_obj_set_width(ui_row2, 976);
    lv_obj_set_height(ui_row2, 52);
    lv_obj_set_x(ui_row2, 0);
    lv_obj_set_y(ui_row2, 0);

    ui_div3 = ui_div__create(ui_ptablelist);
    lv_obj_set_x(ui_div3, 0);
    lv_obj_set_y(ui_div3, 0);

    ui_row3 = ui_cmptablerow4col_create(ui_ptablelist);
    lv_obj_set_x(ui_row3, 0);
    lv_obj_set_y(ui_row3, 0);

    ui_div4 = ui_div__create(ui_ptablelist);
    lv_obj_set_x(ui_div4, 0);
    lv_obj_set_y(ui_div4, 0);

    ui_row4 = ui_cmptablerow4col_create(ui_ptablelist);
    lv_obj_set_x(ui_row4, 0);
    lv_obj_set_y(ui_row4, 0);

    ui_div5 = ui_div__create(ui_ptablelist);
    lv_obj_set_x(ui_div5, 0);
    lv_obj_set_y(ui_div5, 0);

    ui_row5 = ui_cmptablerow4col_create(ui_ptablelist);
    lv_obj_set_x(ui_row5, 0);
    lv_obj_set_y(ui_row5, 0);

    ui_div6 = ui_div__create(ui_ptablelist);
    lv_obj_set_x(ui_div6, 0);
    lv_obj_set_y(ui_div6, 0);

    ui_row6 = ui_cmptablerow4col_create(ui_ptablelist);
    lv_obj_set_x(ui_row6, 0);
    lv_obj_set_y(ui_row6, 0);

    ui_div7 = ui_div__create(ui_ptablelist);
    lv_obj_set_x(ui_div7, 0);
    lv_obj_set_y(ui_div7, 0);

    ui_row7 = ui_cmptablerow4col_create(ui_ptablelist);
    lv_obj_set_x(ui_row7, 0);
    lv_obj_set_y(ui_row7, 0);

    ui_div8 = ui_div__create(ui_ptablelist);
    lv_obj_set_x(ui_div8, 0);
    lv_obj_set_y(ui_div8, 0);

    ui_row8 = ui_cmptablerow4col_create(ui_ptablelist);
    lv_obj_set_x(ui_row8, 0);
    lv_obj_set_y(ui_row8, 0);

    ui_div9 = ui_div__create(ui_ptablelist);
    lv_obj_set_x(ui_div9, 0);
    lv_obj_set_y(ui_div9, 0);

    ui_row9 = ui_cmptablerow4col_create(ui_ptablelist);
    lv_obj_set_x(ui_row9, 0);
    lv_obj_set_y(ui_row9, 0);

    ui_div10 = ui_div__create(ui_ptablelist);
    lv_obj_set_x(ui_div10, 0);
    lv_obj_set_y(ui_div10, 0);

    ui_ppaging = ui_paneleg_create(ui_proot);
    lv_obj_set_width(ui_ppaging, 976);
    lv_obj_set_height(ui_ppaging, 72);
    lv_obj_set_x(ui_ppaging, 24);
    lv_obj_set_y(ui_ppaging, 690);
    lv_obj_set_align(ui_ppaging, LV_ALIGN_TOP_LEFT);

    ui_cellprev = ui_cmpfocuscell_create(ui_ppaging);
    lv_obj_set_width(ui_cellprev, 120);
    lv_obj_set_height(ui_cellprev, 44);
    lv_obj_set_x(ui_cellprev, 696);
    lv_obj_set_y(ui_cellprev, 14);

    lv_label_set_text(ui_comp_get_child(ui_cellprev, UI_COMP_CMPFOCUSCELL_LABEL), "Previous");
    lv_obj_set_style_text_font(ui_comp_get_child(ui_cellprev, UI_COMP_CMPFOCUSCELL_LABEL), &ui_font_WebnarRegular18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ppage = ui_cmpfocuscell_create(ui_ppaging);
    lv_obj_set_width(ui_ppage, 44);
    lv_obj_set_height(ui_ppage, 44);
    lv_obj_set_x(ui_ppage, 830);
    lv_obj_set_y(ui_ppage, 14);

    lv_label_set_text(ui_comp_get_child(ui_ppage, UI_COMP_CMPFOCUSCELL_LABEL), "1");
    lv_obj_set_style_text_font(ui_comp_get_child(ui_ppage, UI_COMP_CMPFOCUSCELL_LABEL), &ui_font_WebnarRegular18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cellnext = ui_cmpfocuscell_create(ui_ppaging);
    lv_obj_set_width(ui_cellnext, 88);
    lv_obj_set_height(ui_cellnext, 44);
    lv_obj_set_x(ui_cellnext, 888);
    lv_obj_set_y(ui_cellnext, 14);

    lv_label_set_text(ui_comp_get_child(ui_cellnext, UI_COMP_CMPFOCUSCELL_LABEL), "Next");
    lv_obj_set_style_text_font(ui_comp_get_child(ui_cellnext, UI_COMP_CMPFOCUSCELL_LABEL), &ui_font_WebnarRegular18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgarrowup = lv_image_create(ui_proot);
    lv_image_set_src(ui_imgarrowup, &ui_img_img_img_arrow_up_png);
    lv_obj_set_width(ui_imgarrowup, 24);
    lv_obj_set_height(ui_imgarrowup, 24);
    lv_obj_set_align(ui_imgarrowup, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgarrowup, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgarrowup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_move_to_index(ui_imgarrowup, 4);
    ui_imgarrowdown = lv_image_create(ui_proot);
    lv_image_set_src(ui_imgarrowdown, &ui_img_img_img_arrow_down_png);
    lv_obj_set_width(ui_imgarrowdown, 24);
    lv_obj_set_height(ui_imgarrowdown, 24);
    lv_obj_set_align(ui_imgarrowdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgarrowdown, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgarrowdown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_move_to_index(ui_imgarrowdown, 5);

}

void ui_ScrFileMgr_screen_destroy(void)
{
    if(ui_ScrFileMgr) lv_obj_del(ui_ScrFileMgr);

    // NULL screen variables
    ui_ScrFileMgr = NULL;
    ui_proot = NULL;
    ui_ptopbar = NULL;
    ui_pfilter = NULL;
    ui_cellall = NULL;
    ui_dtfilter = NULL;
    ui_cellsearch = NULL;
    ui_togglemode = NULL;
    ui_header0 = NULL;
    ui_ptablelist = NULL;
    ui_div0 = NULL;
    ui_row0 = NULL;
    ui_div1 = NULL;
    ui_row1 = NULL;
    ui_div2 = NULL;
    ui_row2 = NULL;
    ui_div3 = NULL;
    ui_row3 = NULL;
    ui_div4 = NULL;
    ui_row4 = NULL;
    ui_div5 = NULL;
    ui_row5 = NULL;
    ui_div6 = NULL;
    ui_row6 = NULL;
    ui_div7 = NULL;
    ui_row7 = NULL;
    ui_div8 = NULL;
    ui_row8 = NULL;
    ui_div9 = NULL;
    ui_row9 = NULL;
    ui_div10 = NULL;
    ui_ppaging = NULL;
    ui_cellprev = NULL;
    ui_ppage = NULL;
    ui_cellnext = NULL;
    ui_imgarrowup = NULL;
    ui_imgarrowdown = NULL;

}
