// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCRFILEMGR_H
#define UI_SCRFILEMGR_H

#ifdef __cplusplus
extern "C" {



#endif

// SCREEN: ui_ScrFileMgr
extern void ui_ScrFileMgr_screen_init(void);

extern void ui_ScrFileMgr_screen_destroy(void);

extern lv_obj_t * ui_ScrFileMgr;
extern lv_obj_t * ui_UPLIST;
extern lv_obj_t * ui_BTN;
extern lv_obj_t * ui_LISTLABEL1;
extern lv_obj_t * ui_year;
extern lv_obj_t * ui_LISTABEL;
extern lv_obj_t * ui_month;
extern lv_obj_t * ui_LISTLABEL2;
extern lv_obj_t * ui_day;
extern lv_obj_t * ui_LISTLABEL3;
extern lv_obj_t * ui_hour;
extern lv_obj_t * ui_LISTLABEL4;
extern lv_obj_t * ui_min;
extern lv_obj_t * ui_LISTLABEL5;
extern lv_obj_t * ui_BTN1;
extern lv_obj_t * ui_BTN2;
extern lv_obj_t * ui_BTN3;
extern lv_obj_t * ui_List_Container;
extern lv_obj_t * ui_List_Header;
extern lv_obj_t * ui_List_Header_Item1;
extern lv_obj_t * ui_List_Header_Item2;
extern lv_obj_t * ui_List_Header_Item3;
extern lv_obj_t * ui_List_Header_Item4;
extern lv_obj_t * ui_DOWNLIST;
extern lv_obj_t * ui_BTN4;
extern lv_obj_t * ui_BTN5;
extern lv_obj_t * ui_BTN6;
extern lv_obj_t * ui_BTN7;
extern lv_obj_t * ui_PlayList[24];
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif