// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_MainPage.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_img_sd_png);    // assets/img/SD.png
LV_IMG_DECLARE(ui_img_1590413862);    // assets/img/HOT-W.png
LV_IMG_DECLARE(ui_img_img_guntype1_png);    // assets/img/GunType1.png
LV_IMG_DECLARE(ui_img_img_enlarge_png);    // assets/img/Enlarge.png
LV_IMG_DECLARE(ui_img_img_wifi_png);    // assets/img/WiFi.png
LV_IMG_DECLARE(ui_img_img_battery1_png);    // assets/img/Battery1.png
LV_IMG_DECLARE(ui_img_img_arrowyawimage_png);    // assets/img/arrowyawimage.png
LV_IMG_DECLARE(ui_img_img_arrowrollimage_png);    // assets/img/arrowrollimage.png
LV_IMG_DECLARE(ui_img_img_arrowpitchimage_png);    // assets/img/arrowpitchimage.png
LV_IMG_DECLARE(ui_img_img_record_png);    // assets/img/record.png
LV_IMG_DECLARE(ui_img_img_lrf_png);    // assets/img/LRF.png
LV_IMG_DECLARE(ui_img_img_dots_png);    // assets/img/Dots.png
LV_IMG_DECLARE(ui_img_img_imagemode_png);    // assets/img/ImageMode.png
LV_IMG_DECLARE(ui_img_img_brightness_png);    // assets/img/Brightness.png
LV_IMG_DECLARE(ui_img_img_contrast_png);    // assets/img/Contrast.png
LV_IMG_DECLARE(ui_img_img_sharpness_png);    // assets/img/Sharpness.png
LV_IMG_DECLARE(ui_img_img_backgroundreflesh_png);    // assets/img/BackGroundReflesh.png
LV_IMG_DECLARE(ui_img_img_ultraclear_png);    // assets/img/UltraClear.png
LV_IMG_DECLARE(ui_img_img_pip_png);    // assets/img/PIP.png
LV_IMG_DECLARE(ui_img_1583056019);    // assets/img/Wi-Fi.png
LV_IMG_DECLARE(ui_img_img_tilt_png);    // assets/img/Tilt.png
LV_IMG_DECLARE(ui_img_img_compass_png);    // assets/img/Compass.png
LV_IMG_DECLARE(ui_img_img_reticle_png);    // assets/img/Reticle.png
LV_IMG_DECLARE(ui_img_img_enter2_png);    // assets/img/Enter2.png
LV_IMG_DECLARE(ui_img_img_ballistic_png);    // assets/img/Ballistic.png
LV_IMG_DECLARE(ui_img_img_microphone_png);    // assets/img/Microphone.png
LV_IMG_DECLARE(ui_img_img_ravrecording_png);    // assets/img/RAVRecording.png
LV_IMG_DECLARE(ui_img_img_standbytimer_png);    // assets/img/StandbyTimer.png
LV_IMG_DECLARE(ui_img_img_compasscalibration_png);    // assets/img/CompassCalibration.png
LV_IMG_DECLARE(ui_img_img_deadpixelrepair_png);    // assets/img/DeadPixelRepair.png
LV_IMG_DECLARE(ui_img_img_statusbar_png);    // assets/img/StatusBar.png
LV_IMG_DECLARE(ui_img_img_deletefile_png);    // assets/img/DeleteFile.png
LV_IMG_DECLARE(ui_img_img_setting_png);    // assets/img/Setting.png

// FONTS
LV_FONT_DECLARE(ui_font_WebnarSemiBold24);
LV_FONT_DECLARE(ui_font_WebnarSemiBold18);
LV_FONT_DECLARE(ui_font_WebnarRegular24);
LV_FONT_DECLARE(ui_font_WebnarItalic32);
LV_FONT_DECLARE(ui_font_WebnarSemiBold12);
LV_FONT_DECLARE(ui_font_WebnarMedium15);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
