// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {

#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"
#include "user/lv_port_indev.h"
#include "user/mainpage_event_handle.h"
#include "user/menu_handle.h"
#include "user/font.h"
#include "user/play_handle.h"
#include "user/timer_handle.h"
#include <time.h>
///////////////////// SCREENS ////////////////////

#include "screens/ui_MainPage.h"
#include "screens/ui_ScrFileMgr.h"
#include "screens/ui_PlayBar.h"

///////////////////// VARIABLES ////////////////////


// EVENTS
extern lv_obj_t * ui____initial_actions0;

#define IMAGES_PATH "A:E:/ZKL-75-6LC/zkl_windows/ui/images/"
#define FONTS_PATH "E:/ZKL-75-6LC/zkl_windows/ui/fonts/"
// FONTS
extern lv_font_t* ui_font_WebnarItalic24;
extern lv_font_t* ui_font_WebnarItalic32;
extern lv_font_t* ui_font_WebnarMedium15;
extern lv_font_t* ui_font_WebnarMedium18;
extern lv_font_t* ui_font_WebnarRegular13;
extern lv_font_t* ui_font_WebnarRegular15;
extern lv_font_t* ui_font_WebnarRegular18;
extern lv_font_t* ui_font_WebnarRegular20;
extern lv_font_t* ui_font_WebnarRegular24;
extern lv_font_t* ui_font_WebnarSemiBold12;
extern lv_font_t* ui_font_WebnarSemiBold18;
extern lv_font_t* ui_font_WebnarSemiBold24;

extern uint8_t g_my_keypad_btn_points[4];
extern lv_indev_t * indev_keypad;
extern lv_group_t * keypad_group;
// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif