// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_transparent[1] = {0x000000};
const ui_theme_variable_t _ui_theme_alpha_transparent[1] = {0};

const ui_theme_variable_t _ui_theme_color_pagebg[1] = {0x323232};
const ui_theme_variable_t _ui_theme_alpha_pagebg[1] = {255};

const ui_theme_variable_t _ui_theme_color_Text[1] = {0xFFFFFF};
const ui_theme_variable_t _ui_theme_alpha_Text[1] = {255};

const ui_theme_variable_t _ui_theme_color_borders1[1] = {0xFAFBFD};
const ui_theme_variable_t _ui_theme_alpha_borders1[1] = {255};

const ui_theme_variable_t _ui_theme_color_bg1[1] = {0x2EEEFC};
const ui_theme_variable_t _ui_theme_alpha_bg1[1] = {128};

const ui_theme_variable_t _ui_theme_color_menubg[1] = {0x2E2D2F};
const ui_theme_variable_t _ui_theme_alpha_menubg[1] = {102};

const ui_theme_variable_t _ui_theme_color_menurowbg[1] = {0x2EEEFC};
const ui_theme_variable_t _ui_theme_alpha_menurowbg[1] = {76};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

