// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_TRANSPARENT 0
#define UI_THEME_COLOR_PAGEBG 1
#define UI_THEME_COLOR_TEXT 2
#define UI_THEME_COLOR_BORDERS1 3
#define UI_THEME_COLOR_BG1 4
#define UI_THEME_COLOR_MENUBG 5
#define UI_THEME_COLOR_MENUROWBG 6

#define UI_THEME_DEFAULT 0

extern const ui_theme_variable_t _ui_theme_color_transparent[1];
extern const ui_theme_variable_t _ui_theme_alpha_transparent[1];

extern const ui_theme_variable_t _ui_theme_color_pagebg[1];
extern const ui_theme_variable_t _ui_theme_alpha_pagebg[1];

extern const ui_theme_variable_t _ui_theme_color_Text[1];
extern const ui_theme_variable_t _ui_theme_alpha_Text[1];

extern const ui_theme_variable_t _ui_theme_color_borders1[1];
extern const ui_theme_variable_t _ui_theme_alpha_borders1[1];

extern const ui_theme_variable_t _ui_theme_color_bg1[1];
extern const ui_theme_variable_t _ui_theme_alpha_bg1[1];

extern const ui_theme_variable_t _ui_theme_color_menubg[1];
extern const ui_theme_variable_t _ui_theme_alpha_menubg[1];

extern const ui_theme_variable_t _ui_theme_color_menurowbg[1];
extern const ui_theme_variable_t _ui_theme_alpha_menurowbg[1];

extern const uint32_t * ui_theme_colors[1];
extern const uint8_t * ui_theme_alphas[1];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
